#2024 51MCM-B题#

首先创建路径邻接矩阵，1代表联通，0代表断开。节点与自身不连通。
然后使用广度优先搜索，搜索出符合条件的五条路径

In [1]:
import numpy as np
from collections import deque
import copy

matrix = np.array([[0, 1, 0, 1, 0, 0, 0, 0, 0],[1, 0, 1, 0, 1, 0, 0, 0, 0],[0, 1, 0, 0, 0, 1, 0, 0, 0],[1, 0, 0, 0, 1, 0, 1, 0, 0],[0, 1, 0, 1, 0, 1, 0, 1, 0],[0, 0, 1, 0, 1, 0, 0, 0, 1],[0, 0, 0, 1, 0, 0, 0, 1, 0],[0, 0, 0, 0, 1, 0, 1, 0, 1],[0, 0, 0, 0, 0, 1, 0, 1, 0]])
#print(matrix)


class Graph:
    def __init__(self):
        self.graph = {0:[]}

    def add_edge(self, node, neighbors):
        self.graph[node]= self.graph.get(node,[]) + [neighbors]

class ResizableList(object):
    def __init__(self, initial_size=1764):
        self.data = [0] * initial_size
        self.size = 0
 
    def __getitem__(self, index):
        if index >= self.size:
            self._resize(index + 1)
        return self.data[index]
 
    def __setitem__(self, index, value):
        if index >= self.size:
            self._resize(index + 1)
        self.data[index] = value
        if index >= self.size:
            self.size = index + 1
 
    def _resize(self, new_size):
        self.data += [0] * (new_size - len(self.data))

In [2]:

g = Graph()
g.add_edge(0,1)
g.add_edge(0,3)
g.add_edge(1,0)
g.add_edge(1,4)
g.add_edge(2,3)
g.add_edge(2,18)
g.add_edge(3,0)
g.add_edge(3,2)
g.add_edge(3,36)
g.add_edge(3,42)
g.add_edge(4,1)
g.add_edge(4,6)
g.add_edge(5,6)
g.add_edge(5,9)
g.add_edge(5,16)
g.add_edge(5,22)
g.add_edge(6,4)
g.add_edge(6,5)
g.add_edge(6,34)
g.add_edge(7,12)
g.add_edge(7,24)
g.add_edge(7,33)
g.add_edge(8,9)
g.add_edge(8,28)
g.add_edge(8,37)
g.add_edge(8,41)
g.add_edge(9,5)
g.add_edge(9,8)
g.add_edge(9,10)
g.add_edge(10,9)
g.add_edge(10,11)
g.add_edge(10,16)
g.add_edge(10,19)
g.add_edge(11,10)
g.add_edge(11,12)
g.add_edge(11,20)
g.add_edge(11,41)
g.add_edge(12,7)
g.add_edge(12,11)
g.add_edge(12,35)
g.add_edge(13,14)
g.add_edge(13,15)
g.add_edge(13,39)
g.add_edge(14,13)
g.add_edge(14,17)
g.add_edge(14,21)
g.add_edge(15,13)
g.add_edge(15,42)
g.add_edge(16,5)
g.add_edge(16,10)
g.add_edge(16,18)
g.add_edge(16,36)
g.add_edge(17,14)
g.add_edge(17,39)
g.add_edge(18,2)
g.add_edge(18,16)
g.add_edge(18,19)
g.add_edge(18,23)
g.add_edge(19,10)
g.add_edge(19,18)
g.add_edge(19,20)
g.add_edge(19,23)
g.add_edge(20,11)
g.add_edge(20,19)
g.add_edge(21,14)
g.add_edge(22,5)
g.add_edge(22,34)
g.add_edge(22,40)
g.add_edge(23,18)
g.add_edge(23,19)
g.add_edge(24,7)
g.add_edge(24,32)
g.add_edge(25,30)
g.add_edge(25,33)
g.add_edge(26,31)
g.add_edge(26,33)
g.add_edge(27,30)
g.add_edge(27,35)
g.add_edge(28,8)
g.add_edge(28,35)
g.add_edge(29,31)
g.add_edge(29,32)
g.add_edge(30,25)
g.add_edge(30,27)
g.add_edge(31,26)
g.add_edge(31,29)
g.add_edge(32,24)
g.add_edge(32,29)
g.add_edge(33,7)
g.add_edge(33,25)
g.add_edge(33,26)
g.add_edge(34,6)
g.add_edge(34,22)
g.add_edge(34,40)
g.add_edge(35,12)
g.add_edge(35,27)
g.add_edge(35,28)
g.add_edge(36,3)
g.add_edge(36,16)
g.add_edge(37,8)
g.add_edge(38,39)
g.add_edge(38,42)
g.add_edge(39,13)
g.add_edge(39,17)
g.add_edge(39,38)
g.add_edge(40,22)
g.add_edge(40,34)
g.add_edge(41,8)
g.add_edge(41,11)
g.add_edge(42,3)
g.add_edge(42,15)
g.add_edge(42,38)
g.add_edge(27,33)
g.add_edge(33,27)
g.add_edge(26,32)
g.add_edge(32,26)
g.add_edge(6,0)
g.add_edge(0,6)
g.add_edge(21,17)
g.add_edge(17,21)
g.add_edge(37,28)
g.add_edge(28,37)
g.add_edge(35,41)
g.add_edge(41,35)
g.add_edge(6,36)
g.add_edge(36,6)
g.add_edge(41,10)
g.add_edge(10,41)
g.add_edge(38,13)
g.add_edge(13,38)
g.add_edge(2,15)
g.add_edge(15,2)


#新添加的路线
g.add_edge(35,33)
g.add_edge(35, 8)
g.add_edge(32,7)
g.add_edge(18,10)
g.add_edge(42,2)
g.add_edge(3,6)
print(g.graph)

def bfs(graph, start, target):
    visited = []
    paths = []
    queue = [[start]]
    if start == target:
        return "Start = target"
    while queue:
        path = queue.pop(0)
        node = path[-1]
        neighbours = graph[node]
        for neighbour in neighbours:
            if(neighbour in path):
                continue
            new_path = list(path)
            new_path.append(neighbour)
            queue.append(new_path)
            if neighbour == target:
                if len(paths) >=5:return paths #更严格的限制
                
                if len(paths) >= 1:
                    if len(new_path) > len(paths[0]):
                        return paths
                
                paths.append(new_path)
        visited.append(node)
    return "No path"

{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42, 6], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [13, 17, 21], 15: [13, 42, 2], 16: [5, 10, 18, 36], 17: [14, 39, 21], 18: [2, 16, 19, 23, 10], 19: [10, 18, 20, 23], 20: [11, 19], 21: [14, 17], 22: [5, 34, 40], 23: [18, 19], 24: [7, 32], 25: [30, 33], 26: [31, 33, 32], 27: [30, 35, 33], 28: [8, 35, 37], 29: [31, 32], 30: [25, 27], 31: [26, 29], 32: [24, 29, 26, 7], 33: [7, 25, 26, 27], 34: [6, 22, 40], 35: [12, 27, 28, 41, 33, 8], 36: [3, 16, 6], 37: [8, 28], 38: [39, 42, 13], 39: [13, 17, 38], 40: [22, 34], 41: [8, 11, 35, 10], 42: [3, 15, 38, 2]}


In [3]:
plans = [[17,6,92],
[22,4,113],
[6,22,101],
[13,26,84],
[11,28,87],
[4,17,62],
[26,15,25],
[27,26,65],
[23,24,49],
[17,29,64],
[19,33,42],
[23,10,102],
[32,34,61],
[22,10,97],
[32,23,113],
[36,18,80],
[27,8,100],
[9,34,114],
[28,20,107],
[27,40,52],
[14,17,46],
[38,33,85],
[26,40,88],
[35,23,61],
[21,19,121],
[32,20,103],
[9,31,102],
[14,6,58],
[7,16,65],
[33,35,55],
[29,9,24],
[20,25,66],
[10,40,64],
[41,7,65],
[17,8,122],
[39,30,61],
[27,17,66],
[25,20,66],
[38,20,91],
[27,6,121],
[6,3,63],
[7,26,89],
[35,22,93],
[40,27,90],
[12,24,98],
[32,39,134],
[21,38,95],
[31,15,82],
[28,40,74],
[2,19,63],
[17,29,84],
[8,37,92],
[37,33,98],
[24,28,101],
[5,40,51],
[38,33,103],
[23,31,110],
[15,20,122],
[13,23,66],
[2,22,72],
[19,23,85],
[15,1,84],
[39,11,54],
[39,29,33],
[40,8,83],
[34,18,86],
[13,4,59],
[23,2,55],
[19,25,115],
[21,13,91],
[18,15,77],
[4,15,64],
[0,5,75],
[23,32,65],
[7,14,89],
[12,3,86],
[40,10,88],
[27,17,52],
[38,14,108],
[24,21,80],
[2,4,85],
[7,26,63],
[8,13,86],
[21,36,82],
[35,39,85],
[4,22,78],
[18,37,63],
[23,16,100],
[8,14,116],
[0,17,73],
[17,0,79],
[0,35,54],
[21,40,103],
[13,23,112],
[28,24,72],
[39,20,97],
[41,21,49],
[7,39,80],
[10,13,47],
[26,28,64]]

l_org = [[0,1,315],
[0,3,393],
[1,0,200],
[1,4,231],
[2,3,667],
[2,18,790],
[3,0,615],
[3,2,424],
[3,36,730],
[3,42,618],
[4,1,200],
[4,6,246],
[5,6,405],
[5,9,545],
[5,16,282],
[5,22,529],
[6,4,200],
[6,5,403],
[6,34,520],
[7,12,829],
[7,24,512],
[7,33,395],
[8,9,517],
[8,28,321],
[8,37,200],
[8,41,276],
[9,5,678],
[9,8,392],
[9,10,389],
[10,9,205],
[10,11,495],
[10,16,574],
[10,19,479],
[11,10,541],
[11,12,561],
[11,20,606],
[11,41,261],
[12,7,758],
[12,11,707],
[12,35,519],
[13,14,419],
[13,15,868],
[13,39,227],
[14,13,513],
[14,17,200],
[14,21,200],
[15,13,598],
[15,42,200],
[16,5,328],
[16,10,554],
[16,18,473],
[16,36,469],
[17,14,290],
[17,39,517],
[18,2,635],
[18,16,576],
[18,19,497],
[18,23,397],
[19,10,453],
[19,18,388],
[19,20,522],
[19,23,506],
[20,11,240],
[20,19,368],
[21,14,210],
[22,5,377],
[22,34,305],
[22,40,230],
[23,18,480],
[23,19,467],
[24,7,472],
[24,32,325],
[25,30,200],
[25,33,316],
[26,31,237],
[26,33,442],
[27,30,350],
[27,35,831],
[28,8,371],
[28,35,418],
[29,31,200],
[29,32,200],
[30,25,289],
[30,27,200],
[31,26,200],
[31,29,200],
[32,24,323],
[32,29,266],
[33,7,200],
[33,25,293],
[33,26,505],
[34,6,279],
[34,22,270],
[34,40,340],
[35,12,410],
[35,27,767],
[35,28,606],
[36,3,501],
[36,16,557],
[37,8,272],
[38,39,407],
[38,42,821],
[39,13,375],
[39,17,315],
[39,38,406],
[40,22,247],
[40,34,200],
[41,8,280],
[41,11,494],
[42,3,974],
[42,15,200],
[42,38,460],
[27,33,442],
[33,27,340],
[26,32,200],
[32,26,289],
[6,0,226],
[0,6,370],
[21,17,321],
[17,21,200],
[37,28,200],
[28,37,272],
[35,41,637],
[41,35,521],
[6,36,200],
[36,6,298],
[41,10,475],
[10,41,483],
[38,13,365],
[13,38,434],
[2,15,688],
[15,2,921],

[35,33,10000],
[35,8,10000],
[32,7,10000],
[18,10,10000],
[42,2,10000],
[3,6,10000]
]

possible_links = [[1,6],
                  [6,1],
[0,4],
[4,0],
[22,6],
[6,22],
[5,34],
[34,5],
[13,17],
[17,13],
[14,39],
[39,14],
[13,42],
[42,13],
[15,38],
[38,15],
[2,42],
[3,6],
[6,3],
[0,36],
[36,0],
[2,36],
[36,2],
[36,18],[18,36],
[3,18],[38,3],
[3,16],[16,3],
[2,16],[16,2],
[5,36],[36,5],
[6,16],[16,6],
[10,18],
[5,10],[10,5],
[9,16],[16,9],
[8,10],[10,8],
[9,41],[41,9],
[10,20],[20,10],
[11,19],[19,11],
[8,35],
[11,35],[35,11],
[12,41],[41,12],
[7,35],[35,7],
[33,35],
[33,12],[12,33],
[30,33],[33,30],
[25,27],[27,25],
[7,32],
[7,26],[26,7],
[33,32],[32,33],
[31,32],[31,32],
[26,29],[29,26],
]

'''
round 1
[35,33],
[12,27],[27,12],
[27,7],[7,27],

round 2
[35,8],
[28,41],[41,28],

round 3
[32,7],
[26,24],[24,26],
[24,33],[33,24],

round 4
[18,10],
[16,19],[19,16],

round 5
[42,2],
[3,15],[15,3],
'''

'\nround 1\n[35,33],\n[12,27],[27,12],\n[27,7],[7,27],\n\nround 2\n[35,8],\n[28,41],[41,28],\n\nround 3\n[32,7],\n[26,24],[24,26],\n[24,33],[33,24],\n\nround 4\n[18,10],\n[16,19],[19,16],\n\nround 5\n[42,2],\n[3,15],[15,3],\n'

In [4]:


def routenum(i,j):
    return 41 * i + j -42

def relationmat(route):
    relmat = ResizableList()
    while route:
        if len(route) == 1:
            break
        i = route.pop(0)
        j = route[0]
        relmat[routenum(i,j)] = 1
    return relmat


In [5]:
def largest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[-n:]
def smallest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[:n]

In [6]:
l = np.zeros(1764)
for l_i in l_org:
    l[routenum(l_i[0],l_i[1])] = l_i[2]


relmat = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    plan.append(len(routes))
    print(len(relmat))
    for route in routes:
        relmat.append(relationmat(route).data)

nprelmat = np.array(relmat)
nprelmat = nprelmat.T
print(nprelmat)


0
1
3
5
6
9
12
17
18
21
26
27
29
34
36
38
39
40
42
45
46
47
48
49
50
51
52
55
58
59
60
62
65
67
70
75
77
82
83
84
85
87
88
89
93
94
98
100
105
106
107
112
113
114
115
116
117
119
120
121
124
125
127
129
134
135
138
141
142
143
144
145
150
151
156
159
160
162
167
168
171
172
173
178
182
185
187
189
190
195
196
197
202
206
207
209
211
213
217
219
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)


##下面使用目标函数min=\Sigmax^2进行梯度下降优化

In [8]:
%%time

Q = nprelmat.T @ nprelmat
print(Q)

A = []
b = []
i = 0
for plan in plans:
    A.append(np.zeros(i).tolist() + np.ones(plan[3]).tolist() + np.zeros(len(Q) - plan[3] - i).tolist())
    b.append(plan[2])
    i += plan[3]
A = np.array(A)

[[5 0 0 ... 0 0 0]
 [0 3 1 ... 0 0 0]
 [0 1 3 ... 0 0 0]
 ...
 [0 0 0 ... 5 3 0]
 [0 0 0 ... 3 5 0]
 [0 0 0 ... 0 0 4]]
CPU times: total: 15.6 ms
Wall time: 127 ms


In [9]:
def evaluate_max_influence(R, p):
    originload = sum(p)
    for k in range(5):
        t = R @ p
        a, _ = max(enumerate(t), key=lambda x: x[1])
        for j in range(len(R[a])):
            if R[a,j] != 0:
                p[j] = 0
    return originload - sum(p)

In [10]:
p = np.ones(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    plan.append(i)
    plan.append(i + plan[3])
    i += plan[3]

In [11]:
%%time
import random
import math
def list_exp(l):
    return [math.exp(x) for x in l]
#p_best = np.ones(len(Q))


CPU times: total: 0 ns
Wall time: 0 ns


In [12]:
%%time
import random
def back_fire(nprelmat, p_best):
    p = p_best
    latestmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
    max_best = latestmax
    T = 0.01
    for i in range(150000):
        fromchange = random.randint(0,len(p) - 1)
        changeamount = 0.5 * (random.random() - 0.5) * (p[fromchange]+1)
        if p[fromchange] + changeamount < 0: 
            continue
        
        p[fromchange] += changeamount
        if min(l - nprelmat @ p) < 0: 
            p[fromchange] -= changeamount
            continue
        if max(A @ p - b) > 0: 
            p[fromchange] -= changeamount
            continue
        tmpmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
        
        if random.random() > np.exp((tmpmax - latestmax) / T):
            p[fromchange] -= changeamount
            latestmax = tmpmax
            #print("cycle:", i, "tmp:", tmpmax)
            continue
        if tmpmax > latestmax:
            latestmax = tmpmax
            
            if latestmax > max_best: 
                max_best = latestmax
                p_best = copy.deepcopy(p)
                print("cycle:", i, "max:", latestmax)
        T = 0.999 * T
    return np.append(max_best, p_best)


def back_fire_Q2(nprelmat, p_best):
    p = p_best
    latestmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
    max_best = latestmax
    T = 0.01
    for i in range(20000):
        fromchange = random.randint(0,len(p) - 1)
        changeamount = 0.5 * (random.random() - 0.5) * (p[fromchange]+1)
        if p[fromchange] + changeamount < 0: 
            continue
        p[fromchange] += changeamount
        #此处删去了限制不超过通行能力的限制
        if max(A @ p - b) > 0: 
            p[fromchange] -= changeamount
            continue
        tmpmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))

        if random.random() > np.exp((tmpmax - latestmax) / T):
            p[fromchange] -= changeamount
            latestmax = tmpmax
            #print("cycle:", i, "tmp:", tmpmax)
            continue
        if tmpmax > latestmax:
            latestmax = tmpmax
            
            
            if latestmax > max_best: 
                max_best = latestmax
                p_best = copy.deepcopy(p)
                print("cycle:", i, "max:", latestmax)
        T = 0.999 * T
    return np.append(max_best, p_best)

CPU times: total: 0 ns
Wall time: 0 ns


In [13]:
print(back_fire(nprelmat,np.ones(len(Q))))

cycle: 1 max: 86.21074677311785
cycle: 3 max: 86.25955478545711
cycle: 4 max: 86.3201153637828
cycle: 10 max: 86.70290235394668
cycle: 15 max: 87.00494336560826
cycle: 24 max: 87.47691827567152
cycle: 29 max: 87.58315728635907
cycle: 31 max: 87.97909243833092
cycle: 33 max: 88.46966975545448
cycle: 37 max: 88.4696697554545
cycle: 40 max: 88.6937414019342
cycle: 41 max: 88.69374140193423
cycle: 42 max: 89.08616302837405
cycle: 45 max: 89.54309507794889
cycle: 52 max: 89.76374818466113
cycle: 55 max: 90.00421580779047
cycle: 60 max: 90.18603347360721
cycle: 62 max: 90.37497314015647
cycle: 74 max: 90.4968436185791
cycle: 80 max: 90.82556267130255
cycle: 81 max: 91.06509627935924
cycle: 82 max: 91.06509627935927
cycle: 83 max: 91.12441755336243
cycle: 86 max: 91.22500679843284
cycle: 92 max: 91.71994889005242
cycle: 93 max: 92.04544795631918
cycle: 94 max: 92.04544795631921
cycle: 98 max: 92.52203860277757
cycle: 99 max: 92.5220386027776
cycle: 102 max: 92.65940820759911
cycle: 111 max: 9

<timed exec>:22: RuntimeWarning: overflow encountered in exp


cycle: 566 max: 114.58369614357991
cycle: 568 max: 114.98389427365203
cycle: 570 max: 115.2824401853448
cycle: 574 max: 115.6928766966563
cycle: 578 max: 116.0794957759719
cycle: 584 max: 116.74250621502034
cycle: 586 max: 116.983878967793
cycle: 587 max: 117.2618085021468
cycle: 592 max: 117.81255616711056
cycle: 597 max: 117.99015829741904
cycle: 600 max: 118.28871863883063
cycle: 602 max: 118.38716980224223
cycle: 607 max: 118.39572527297372
cycle: 610 max: 118.61804903481243
cycle: 615 max: 118.90579509357966
cycle: 616 max: 119.17437975777739
cycle: 617 max: 119.59348116532601
cycle: 618 max: 120.02056489141353
cycle: 619 max: 120.41949883949448
cycle: 620 max: 120.9382978295497
cycle: 623 max: 121.10209919681563
cycle: 626 max: 121.51617452369149
cycle: 630 max: 121.5539895940745
cycle: 633 max: 121.97123790621464
cycle: 635 max: 122.48580073166443
cycle: 649 max: 122.74437463166191
cycle: 654 max: 122.77791744941567
cycle: 667 max: 122.95950349780304
cycle: 672 max: 123.40063342

In [14]:
import csv
# 保存列表到CSV文件
with open("E:\\Q4_result_path_notoptimized-pro5.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q4_result_res_notoptimized-pro5.csv", p0, fmt='%f', delimiter=',')

NameError: name 'p0' is not defined

In [ ]:
'''
import csv
# 保存列表到CSV文件
with open("E:\\Q4_result_path0.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q4_result_res0.csv", p, fmt='%f', delimiter=',')
'''

'\nimport csv\n# 保存列表到CSV文件\nwith open("E:\\Q4_result_path0.csv", \'w\', newline=\'\') as f:\n    writer = csv.writer(f)\n    for routes in routess:\n        writer.writerow([routes])\n\n\n#np.savetxt("E:\\Q1_result_path.csv", routess, fmt=\'%d\', delimiter=\',\')\nnp.savetxt("E:\\Q4_result_res0.csv", p, fmt=\'%f\', delimiter=\',\')\n'

In [ ]:
'''
load = [x for x in nprelmat @ p if x != 0]
print("stream:", load)
import copy
print(evaluate_max_influence(nprelmat, copy.deepcopy(p)))
'''

'\nload = [x for x in nprelmat @ p if x != 0]\nprint("stream:", load)\nimport copy\nprint(evaluate_max_influence(nprelmat, copy.deepcopy(p)))\n'