#2024 51MCM-B题#

首先创建路径邻接矩阵，1代表联通，0代表断开。节点与自身不连通。
然后使用广度优先搜索，搜索出符合条件的五条路径

In [1]:
import numpy as np
from collections import deque
import copy

matrix = np.array([[0, 1, 0, 1, 0, 0, 0, 0, 0],[1, 0, 1, 0, 1, 0, 0, 0, 0],[0, 1, 0, 0, 0, 1, 0, 0, 0],[1, 0, 0, 0, 1, 0, 1, 0, 0],[0, 1, 0, 1, 0, 1, 0, 1, 0],[0, 0, 1, 0, 1, 0, 0, 0, 1],[0, 0, 0, 1, 0, 0, 0, 1, 0],[0, 0, 0, 0, 1, 0, 1, 0, 1],[0, 0, 0, 0, 0, 1, 0, 1, 0]])
#print(matrix)


class Graph:
    def __init__(self):
        self.graph = {0:[]}

    def add_edge(self, node, neighbors):
        self.graph[node]= self.graph.get(node,[]) + [neighbors]

class ResizableList(object):
    def __init__(self, initial_size=1764):
        self.data = [0] * initial_size
        self.size = 0
 
    def __getitem__(self, index):
        if index >= self.size:
            self._resize(index + 1)
        return self.data[index]
 
    def __setitem__(self, index, value):
        if index >= self.size:
            self._resize(index + 1)
        self.data[index] = value
        if index >= self.size:
            self.size = index + 1
 
    def _resize(self, new_size):
        self.data += [0] * (new_size - len(self.data))

In [2]:

g = Graph()
g.add_edge(0,1)
g.add_edge(0,3)
g.add_edge(1,0)
g.add_edge(1,4)
g.add_edge(2,3)
g.add_edge(2,18)
g.add_edge(3,0)
g.add_edge(3,2)
g.add_edge(3,36)
g.add_edge(3,42)
g.add_edge(4,1)
g.add_edge(4,6)
g.add_edge(5,6)
g.add_edge(5,9)
g.add_edge(5,16)
g.add_edge(5,22)
g.add_edge(6,4)
g.add_edge(6,5)
g.add_edge(6,34)
g.add_edge(7,12)
g.add_edge(7,24)
g.add_edge(7,33)
g.add_edge(8,9)
g.add_edge(8,28)
g.add_edge(8,37)
g.add_edge(8,41)
g.add_edge(9,5)
g.add_edge(9,8)
g.add_edge(9,10)
g.add_edge(10,9)
g.add_edge(10,11)
g.add_edge(10,16)
g.add_edge(10,19)
g.add_edge(11,10)
g.add_edge(11,12)
g.add_edge(11,20)
g.add_edge(11,41)
g.add_edge(12,7)
g.add_edge(12,11)
g.add_edge(12,35)
g.add_edge(13,14)
g.add_edge(13,15)
g.add_edge(13,39)
g.add_edge(14,13)
g.add_edge(14,17)
g.add_edge(14,21)
g.add_edge(15,13)
g.add_edge(15,42)
g.add_edge(16,5)
g.add_edge(16,10)
g.add_edge(16,18)
g.add_edge(16,36)
g.add_edge(17,14)
g.add_edge(17,39)
g.add_edge(18,2)
g.add_edge(18,16)
g.add_edge(18,19)
g.add_edge(18,23)
g.add_edge(19,10)
g.add_edge(19,18)
g.add_edge(19,20)
g.add_edge(19,23)
g.add_edge(20,11)
g.add_edge(20,19)
g.add_edge(21,14)
g.add_edge(22,5)
g.add_edge(22,34)
g.add_edge(22,40)
g.add_edge(23,18)
g.add_edge(23,19)
g.add_edge(24,7)
g.add_edge(24,32)
g.add_edge(25,30)
g.add_edge(25,33)
g.add_edge(26,31)
g.add_edge(26,33)
g.add_edge(27,30)
g.add_edge(27,35)
g.add_edge(28,8)
g.add_edge(28,35)
g.add_edge(29,31)
g.add_edge(29,32)
g.add_edge(30,25)
g.add_edge(30,27)
g.add_edge(31,26)
g.add_edge(31,29)
g.add_edge(32,24)
g.add_edge(32,29)
g.add_edge(33,7)
g.add_edge(33,25)
g.add_edge(33,26)
g.add_edge(34,6)
g.add_edge(34,22)
g.add_edge(34,40)
g.add_edge(35,12)
g.add_edge(35,27)
g.add_edge(35,28)
g.add_edge(36,3)
g.add_edge(36,16)
g.add_edge(37,8)
g.add_edge(38,39)
g.add_edge(38,42)
g.add_edge(39,13)
g.add_edge(39,17)
g.add_edge(39,38)
g.add_edge(40,22)
g.add_edge(40,34)
g.add_edge(41,8)
g.add_edge(41,11)
g.add_edge(42,3)
g.add_edge(42,15)
g.add_edge(42,38)
g.add_edge(27,33)
g.add_edge(33,27)
g.add_edge(26,32)
g.add_edge(32,26)
g.add_edge(6,0)
g.add_edge(0,6)
g.add_edge(21,17)
g.add_edge(17,21)
g.add_edge(37,28)
g.add_edge(28,37)
g.add_edge(35,41)
g.add_edge(41,35)
g.add_edge(6,36)
g.add_edge(36,6)
g.add_edge(41,10)
g.add_edge(10,41)
g.add_edge(38,13)
g.add_edge(13,38)
g.add_edge(2,15)
g.add_edge(15,2)


#新添加的路线
g.add_edge(35,33)
g.add_edge(35, 8)
g.add_edge(32,7)
g.add_edge(18,10)
g.add_edge(42,2)
g.add_edge(16,2)

print(g.graph)

def bfs(graph, start, target):
    visited = []
    paths = []
    queue = [[start]]
    if start == target:
        return "Start = target"
    while queue:
        path = queue.pop(0)
        node = path[-1]
        neighbours = graph[node]
        for neighbour in neighbours:
            if(neighbour in path):
                continue
            new_path = list(path)
            new_path.append(neighbour)
            queue.append(new_path)
            if neighbour == target:
                if len(paths) >=5:return paths #更严格的限制
                
                if len(paths) >= 1:
                    if len(new_path) > len(paths[0]):
                        return paths
                
                paths.append(new_path)
        visited.append(node)
    return "No path"

{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [13, 17, 21], 15: [13, 42, 2], 16: [5, 10, 18, 36, 2], 17: [14, 39, 21], 18: [2, 16, 19, 23, 10], 19: [10, 18, 20, 23], 20: [11, 19], 21: [14, 17], 22: [5, 34, 40], 23: [18, 19], 24: [7, 32], 25: [30, 33], 26: [31, 33, 32], 27: [30, 35, 33], 28: [8, 35, 37], 29: [31, 32], 30: [25, 27], 31: [26, 29], 32: [24, 29, 26, 7], 33: [7, 25, 26, 27], 34: [6, 22, 40], 35: [12, 27, 28, 41, 33, 8], 36: [3, 16, 6], 37: [8, 28], 38: [39, 42, 13], 39: [13, 17, 38], 40: [22, 34], 41: [8, 11, 35, 10], 42: [3, 15, 38, 2]}


In [3]:
plans = [[17,6,92],
[22,4,113],
[6,22,101],
[13,26,84],
[11,28,87],
[4,17,62],
[26,15,25],
[27,26,65],
[23,24,49],
[17,29,64],
[19,33,42],
[23,10,102],
[32,34,61],
[22,10,97],
[32,23,113],
[36,18,80],
[27,8,100],
[9,34,114],
[28,20,107],
[27,40,52],
[14,17,46],
[38,33,85],
[26,40,88],
[35,23,61],
[21,19,121],
[32,20,103],
[9,31,102],
[14,6,58],
[7,16,65],
[33,35,55],
[29,9,24],
[20,25,66],
[10,40,64],
[41,7,65],
[17,8,122],
[39,30,61],
[27,17,66],
[25,20,66],
[38,20,91],
[27,6,121],
[6,3,63],
[7,26,89],
[35,22,93],
[40,27,90],
[12,24,98],
[32,39,134],
[21,38,95],
[31,15,82],
[28,40,74],
[2,19,63],
[17,29,84],
[8,37,92],
[37,33,98],
[24,28,101],
[5,40,51],
[38,33,103],
[23,31,110],
[15,20,122],
[13,23,66],
[2,22,72],
[19,23,85],
[15,1,84],
[39,11,54],
[39,29,33],
[40,8,83],
[34,18,86],
[13,4,59],
[23,2,55],
[19,25,115],
[21,13,91],
[18,15,77],
[4,15,64],
[0,5,75],
[23,32,65],
[7,14,89],
[12,3,86],
[40,10,88],
[27,17,52],
[38,14,108],
[24,21,80],
[2,4,85],
[7,26,63],
[8,13,86],
[21,36,82],
[35,39,85],
[4,22,78],
[18,37,63],
[23,16,100],
[8,14,116],
[0,17,73],
[17,0,79],
[0,35,54],
[21,40,103],
[13,23,112],
[28,24,72],
[39,20,97],
[41,21,49],
[7,39,80],
[10,13,47],
[26,28,64]]

l_org = [[0,1,315],
[0,3,393],
[1,0,200],
[1,4,231],
[2,3,667],
[2,18,790],
[3,0,615],
[3,2,424],
[3,36,730],
[3,42,618],
[4,1,200],
[4,6,246],
[5,6,405],
[5,9,545],
[5,16,282],
[5,22,529],
[6,4,200],
[6,5,403],
[6,34,520],
[7,12,829],
[7,24,512],
[7,33,395],
[8,9,517],
[8,28,321],
[8,37,200],
[8,41,276],
[9,5,678],
[9,8,392],
[9,10,389],
[10,9,205],
[10,11,495],
[10,16,574],
[10,19,479],
[11,10,541],
[11,12,561],
[11,20,606],
[11,41,261],
[12,7,758],
[12,11,707],
[12,35,519],
[13,14,419],
[13,15,868],
[13,39,227],
[14,13,513],
[14,17,200],
[14,21,200],
[15,13,598],
[15,42,200],
[16,5,328],
[16,10,554],
[16,18,473],
[16,36,469],
[17,14,290],
[17,39,517],
[18,2,635],
[18,16,576],
[18,19,497],
[18,23,397],
[19,10,453],
[19,18,388],
[19,20,522],
[19,23,506],
[20,11,240],
[20,19,368],
[21,14,210],
[22,5,377],
[22,34,305],
[22,40,230],
[23,18,480],
[23,19,467],
[24,7,472],
[24,32,325],
[25,30,200],
[25,33,316],
[26,31,237],
[26,33,442],
[27,30,350],
[27,35,831],
[28,8,371],
[28,35,418],
[29,31,200],
[29,32,200],
[30,25,289],
[30,27,200],
[31,26,200],
[31,29,200],
[32,24,323],
[32,29,266],
[33,7,200],
[33,25,293],
[33,26,505],
[34,6,279],
[34,22,270],
[34,40,340],
[35,12,410],
[35,27,767],
[35,28,606],
[36,3,501],
[36,16,557],
[37,8,272],
[38,39,407],
[38,42,821],
[39,13,375],
[39,17,315],
[39,38,406],
[40,22,247],
[40,34,200],
[41,8,280],
[41,11,494],
[42,3,974],
[42,15,200],
[42,38,460],
[27,33,442],
[33,27,340],
[26,32,200],
[32,26,289],
[6,0,226],
[0,6,370],
[21,17,321],
[17,21,200],
[37,28,200],
[28,37,272],
[35,41,637],
[41,35,521],
[6,36,200],
[36,6,298],
[41,10,475],
[10,41,483],
[38,13,365],
[13,38,434],
[2,15,688],
[15,2,921],

[35,33,10000],
[35,8,10000],
[32,7,10000],
[18,10,10000],
[42,2,10000],
[16,2,10000]
]

possible_links = [[1,6],
                  [6,1],
[0,4],
[4,0],
[22,6],
[6,22],
[5,34],
[34,5],
[13,17],
[17,13],
[14,39],
[39,14],
[13,42],
[42,13],
[15,38],
[38,15],
[2,42],
[3,6],
[6,3],
[0,36],
[36,0],
[2,36],
[36,2],
[36,18],[18,36],
[3,18],[38,3],
[3,16],[16,3],
[2,16],[16,2],
[5,36],[36,5],
[6,16],[16,6],
[10,18],
[5,10],[10,5],
[9,16],[16,9],
[8,10],[10,8],
[9,41],[41,9],
[10,20],[20,10],
[11,19],[19,11],
[8,35],
[11,35],[35,11],
[12,41],[41,12],
[7,35],[35,7],
[33,35],
[33,12],[12,33],
[30,33],[33,30],
[25,27],[27,25],
[7,32],
[7,26],[26,7],
[33,32],[32,33],
[31,32],[31,32],
[26,29],[29,26],
]

'''
round 1
[35,33],
[12,27],[27,12],
[27,7],[7,27],

round 2
[35,8],
[28,41],[41,28],

round 3
[32,7],
[26,24],[24,26],
[24,33],[33,24],

round 4
[18,10],
[16,19],[19,16],

round 5
[42,2],
[3,15],[15,3],
'''

'\nround 1\n[35,33],\n[12,27],[27,12],\n[27,7],[7,27],\n\nround 2\n[35,8],\n[28,41],[41,28],\n\nround 3\n[32,7],\n[26,24],[24,26],\n[24,33],[33,24],\n\nround 4\n[18,10],\n[16,19],[19,16],\n\nround 5\n[42,2],\n[3,15],[15,3],\n'

In [4]:


def routenum(i,j):
    return 41 * i + j -42

def relationmat(route):
    relmat = ResizableList()
    while route:
        if len(route) == 1:
            break
        i = route.pop(0)
        j = route[0]
        relmat[routenum(i,j)] = 1
    return relmat


In [5]:
def largest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[-n:]
def smallest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[:n]

In [6]:
l = np.zeros(1764)
for l_i in l_org:
    l[routenum(l_i[0],l_i[1])] = l_i[2]


relmat = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    plan.append(len(routes))
    print(len(relmat))
    for route in routes:
        relmat.append(relationmat(route).data)

nprelmat = np.array(relmat)
nprelmat = nprelmat.T
print(nprelmat)


0
2
4
6
7
10
13
16
17


20
25
26
28
33
35
37
38
39
41
44
45
46
47
48
49
50
51
54
59
60
61
63
66
68
71
76
78
80
81
82
83
85
86
87
91
92
93
95
99
100
101
106
107
108
109
110
111
113
114
115
116
117
119
121
126
127
130
135
136
137
138
139
144
145
150
151
153
155
157
158
159
162
163
166
170
171
173
175
176
179
180
181
186
191
192
194
196
197
198
199
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)


##下面使用目标函数min=\Sigmax^2进行梯度下降优化

In [8]:
%%time

Q = nprelmat.T @ nprelmat
print(Q)

A = []
b = []
i = 0
for plan in plans:
    A.append(np.zeros(i).tolist() + np.ones(plan[3]).tolist() + np.zeros(len(Q) - plan[3] - i).tolist())
    b.append(plan[2])
    i += plan[3]
A = np.array(A)

[[6 4 0 ... 0 0 0]
 [4 6 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 8 4 0]
 [0 0 0 ... 4 4 0]
 [0 0 0 ... 0 0 4]]
CPU times: total: 78.1 ms
Wall time: 94 ms


In [9]:
def evaluate_max_influence(R, p):
    originload = sum(p)
    for k in range(5):
        t = R @ p
        a, _ = max(enumerate(t), key=lambda x: x[1])
        for j in range(len(R[a])):
            if R[a,j] != 0:
                p[j] = 0
    return originload - sum(p)

In [10]:
p = np.ones(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    plan.append(i)
    plan.append(i + plan[3])
    i += plan[3]

In [11]:
%%time
import random
import math
def list_exp(l):
    return [math.exp(x) for x in l]
#p_best = np.ones(len(Q))


CPU times: total: 0 ns
Wall time: 0 ns


In [12]:
%%time
import random
def back_fire(nprelmat, p_best):
    p = p_best
    latestmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
    max_best = latestmax
    T = 1
    for i in range(50000):
        fromchange = random.randint(0,len(p) - 1)
        changeamount = 0.5 * (random.random() - 0.5) * (p[fromchange]+1)
        if p[fromchange] + changeamount < 0: 
            continue
        
        p[fromchange] += changeamount
        if min(l - nprelmat @ p) < 0: 
            p[fromchange] -= changeamount
            continue
        if max(A @ p - b) > 0: 
            p[fromchange] -= changeamount
            continue
        tmpmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
        
        if random.random() > np.exp((tmpmax - latestmax) / T):
            p[fromchange] -= changeamount
            latestmax = tmpmax
            #print("cycle:", i, "tmp:", tmpmax)
            continue
        if tmpmax > latestmax:
            latestmax = tmpmax
            
            if latestmax > max_best: 
                max_best = latestmax
                p_best = copy.deepcopy(p)
                print("cycle:", i, "max:", latestmax)
        T = 0.999 * T
    return np.append(max_best, p_best)


def back_fire_Q2(nprelmat, p_best):
    p = p_best
    latestmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
    max_best = latestmax
    T = 0.01
    for i in range(20000):
        fromchange = random.randint(0,len(p) - 1)
        changeamount = 0.5 * (random.random() - 0.5) * (p[fromchange]+1)
        if p[fromchange] + changeamount < 0: 
            continue
        p[fromchange] += changeamount
        #此处删去了限制不超过通行能力的限制
        if max(A @ p - b) > 0: 
            p[fromchange] -= changeamount
            continue
        tmpmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))

        if random.random() > np.exp((tmpmax - latestmax) / T):
            p[fromchange] -= changeamount
            latestmax = tmpmax
            #print("cycle:", i, "tmp:", tmpmax)
            continue
        if tmpmax > latestmax:
            latestmax = tmpmax
            
            
            if latestmax > max_best: 
                max_best = latestmax
                p_best = copy.deepcopy(p)
                print("cycle:", i, "max:", latestmax)
        T = 0.999 * T
    return np.append(max_best, p_best)

CPU times: total: 0 ns
Wall time: 0 ns


In [18]:
p = back_fire(nprelmat,p)



<timed exec>:22: RuntimeWarning: overflow encountered in exp


cycle: 2 max: 3848.9169745903837
cycle: 13 max: 3849.200489022881
cycle: 59 max: 3849.2544312052823
cycle: 337 max: 3850.774240793447
cycle: 349 max: 3851.439763875804
cycle: 374 max: 3852.6962895235033
cycle: 77358 max: 3853.245600568447
cycle: 77364 max: 3855.6181936232483
cycle: 77365 max: 3855.661564015806
cycle: 77367 max: 3855.9890556335336
cycle: 92605 max: 3856.350325745182
cycle: 92632 max: 3864.3565602742483
cycle: 92676 max: 3866.814840840053
cycle: 92678 max: 3867.6181752506445


AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [19]:
p = p.tolist()
print(p.pop(0))


3867.6181752506445


In [20]:
print(p)

[39.222582863086195, 49.27392241451759, 25.656539639614124, 81.63792434645686, 43.1853519656224, 51.044360685946685, 4.873985272168395, 35.04101535450655, 26.87459004157877, 17.825095682931327, 7.475128259302277, 36.56443988204773, 14.189786526593066, 0.36998535983783354, 1.7573317677569038, 0.06874967704801094, 64.86947005747655, 30.556006038405318, 5.407206284661626, 12.720488179804729, 1.9992261693515523, 0.20419801902335594, 0.4506362822194751, 5.022343973319043, 25.94133197349042, 8.797874931924964, 45.958781703594084, 54.44947725266623, 2.2195014689402512, 3.4399619106262733, 0.13313385405269995, 1.5502407914422762, 0.15703350916318845, 50.03601506222712, 44.1784253644104, 11.626296167232432, 96.18729919114229, 78.41970736633067, 98.98098843439288, 102.34462576387986, 5.703091115120286, 47.05830509015554, 23.59395754267956, 32.70161313788416, 0.783663671052867, 45.75597261167253, 0.2534943108111974, 56.56664071865846, 60.837372702016, 0.6023563380347471, 74.45522152327712, 27.345

%%time
import copy

p0 = back_fire(nprelmat, np.ones(len(Q)))
p0 = p0.tolist()
effectiveness = p0.pop(0)

len_possible_links = len(possible_links)
hope_passes = np.zeros(len_possible_links)
for k in range(len_possible_links):
    possible_link = possible_links[k]
    for i in range(len(routess)):
        for j in range(len(routess[i]) - 2):
            if routess[i][j] == possible_link[0]:
                if routess[i][j+2] == possible_link[1]:
                    hope_passes[k] += p0[i]
                break

p_norestrict = back_fire_Q2(nprelmat, copy.deepcopy(p0))
p_norestrict = p_norestrict.tolist()
effectiveness_norestrict = p_norestrict.pop(0)
shortness_map = l - nprelmat @ p_norestrict

shortness_links = np.zeros(len_possible_links)
for i in range(len(possible_links)):
    routes = bfs(g.graph, possible_links[i][0], possible_links[i][1])
    for route in routes:
        for j in range(len(route) - 1):
            shortness_links[i] += shortness_map[routenum(route[j],route[j+1])]

neednesses = np.zeros(len_possible_links)
for i in range(len_possible_links):
    neednesses[i] = min(shortness_links[i], hope_passes[i])
    
print(max(neednesses), largest_n_indices(neednesses, 5))
for i in largest_n_indices(neednesses, 5):
    print(possible_links[i])
%%time
import copy

p0 = back_fire(nprelmat, np.ones(len(Q)))
p0 = p0.tolist()
effectiveness = p0.pop(0)

len_possible_links = len(possible_links)
hope_passes = np.zeros(len_possible_links)
for k in range(len_possible_links):
    possible_link = possible_links[k]
    for i in range(len(routess)):
        for j in range(len(routess[i]) - 2):
            if routess[i][j] == possible_link[0]:
                if routess[i][j+2] == possible_link[1]:
                    hope_passes[k] += p0[i]
                break

p_norestrict = back_fire_Q2(nprelmat, copy.deepcopy(p0))
p_norestrict = p_norestrict.tolist()
effectiveness_norestrict = p_norestrict.pop(0)
shortness_map = l - nprelmat @ p_norestrict

shortness_links = np.zeros(len_possible_links)
for i in range(len(possible_links)):
    routes = bfs(g.graph, possible_links[i][0], possible_links[i][1])
    for route in routes:
        for j in range(len(route) - 1):
            shortness_links[i] += shortness_map[routenum(route[j],route[j+1])]

neednesses = np.zeros(len_possible_links)
for i in range(len_possible_links):
    neednesses[i] = min(shortness_links[i], hope_passes[i])
    
print(max(neednesses), largest_n_indices(neednesses, 5))
for i in largest_n_indices(neednesses, 5):
    print(possible_links[i])


%%time
import copy

p0 = back_fire(nprelmat, np.ones(len(Q)))
p0 = p0.tolist()
effectiveness = p0.pop(0)

len_possible_links = len(possible_links)
hope_passes = np.zeros(len_possible_links)
for k in range(len_possible_links):
    possible_link = possible_links[k]
    for i in range(len(routess)):
        for j in range(len(routess[i]) - 2):
            if routess[i][j] == possible_link[0]:
                if routess[i][j+2] == possible_link[1]:
                    hope_passes[k] += p0[i]
                break

p_norestrict = back_fire_Q2(nprelmat, copy.deepcopy(p0))
p_norestrict = p_norestrict.tolist()
effectiveness_norestrict = p_norestrict.pop(0)
shortness_map = l - nprelmat @ p_norestrict

shortness_links = np.zeros(len_possible_links)
for i in range(len(possible_links)):
    routes = bfs(g.graph, possible_links[i][0], possible_links[i][1])
    for route in routes:
        for j in range(len(route) - 1):
            shortness_links[i] += shortness_map[routenum(route[j],route[j+1])]

neednesses = np.zeros(len_possible_links)
for i in range(len_possible_links):
    neednesses[i] = min(shortness_links[i], hope_passes[i])
    
print(max(neednesses), largest_n_indices(neednesses, 5))
for i in largest_n_indices(neednesses, 5):
    print(possible_links[i])


In [ ]:
import csv
# 保存列表到CSV文件
with open("E:\\Q4_result_path_notoptimized-pro1.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q4_result_res_notoptimized-pro1.csv", p0, fmt='%f', delimiter=',')

In [ ]:
'''
import csv
# 保存列表到CSV文件
with open("E:\\Q4_result_path0.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q4_result_res0.csv", p, fmt='%f', delimiter=',')
'''

'\nimport csv\n# 保存列表到CSV文件\nwith open("E:\\Q4_result_path0.csv", \'w\', newline=\'\') as f:\n    writer = csv.writer(f)\n    for routes in routess:\n        writer.writerow([routes])\n\n\n#np.savetxt("E:\\Q1_result_path.csv", routess, fmt=\'%d\', delimiter=\',\')\nnp.savetxt("E:\\Q4_result_res0.csv", p, fmt=\'%f\', delimiter=\',\')\n'

In [ ]:
'''
load = [x for x in nprelmat @ p if x != 0]
print("stream:", load)
import copy
print(evaluate_max_influence(nprelmat, copy.deepcopy(p)))
'''

'\nload = [x for x in nprelmat @ p if x != 0]\nprint("stream:", load)\nimport copy\nprint(evaluate_max_influence(nprelmat, copy.deepcopy(p)))\n'

In [17]:
p = [3.84603130e+03,3.26334451e+01,5.54423476e+01,1.35020242e+01,9.71247491e+01,4.69556873e+01,5.17446871e01,8.30238534e-01,3.96367721e+01,3.02502711e+01,1.45422090e+01,2.54516798e+01,1.78048195e+01,1.65792563e+01,5.99502088e+00,2.19216226e+00,8.30757200e-01,6.47333448e+01,1.68705387e+01,7.55489838e+00,2.36720493e+01,5.30350342e+00,1.31004049e+00,2.45852373e+00,1.22658618e+00,3.17580342e-02,2.07489457e+01,4.43390713e+01,5.73989991e+01,1.12066012e+00,6.58668664e-02,5.40750439e-01,4.33790146e-01,2.72242797e-01,4.81153100e+01,4.60938219e+01,2.08673201e+01,5.36654633e+01,7.96754089e+01,9.99796410e+01,9.83151533e+01,1.38153274e+01,3.49659419e+01,2.41207873e+01,4.73570760e+01,2.24206374e+00,4.46857597e+01,1.50830978e+00,7.95600825e+01,5.94376840e+01,3.46728667e-02,9.67975137e+01,5.19589266e+01,1.38223752e+01,1.33207396e+01,5.57381944e+00,1.16992555e+01,1.74671335e+01,1.24410637e+01,6.35075212e+00,2.05388319e+01,5.17240382e+01,2.24676979e-02,1.68721275e+01,4.58079520e+01,1.75420705e+01,6.82644979e-01,5.50420688e+01,4.40988102e+00,2.29693993e+01,4.14737904e+01,3.84470752e-01,4.98149308e-01,1.13289863e+00,7.85061569e+00,2.72873665e+01,1.84286966e+01,1.03922480e+00,3.84608017e+01,1.76384358e+00,7.84383087e+00,4.05911857e+01,6.98310780e+01,9.81667305e+01,2.96243378e+01,3.32557237e+01,8.56167300e+01,9.11883323e+01,4.95390122e+01,2.68093691e+01,3.96840673e+00,9.29915327e+00,9.42810860e+01,1.61736198e+00,2.36282405e+01,6.51464929e+01,1.14151511e-02,1.13640402e+01,6.43421602e-01,2.33207501e+00,3.38258996e+01,4.38522801e+01,6.31939667e+00,1.60213832e-01,2.06161000e+00,1.06079569e-01,1.79858129e-01,9.19588027e+01,7.75707016e+01,9.96114729e+01,5.05979329e+01,2.27585284e+00,3.22497455e+00,7.54268480e+01,1.26210028e+01,2.73404495e+01,6.86414083e+01,8.48927808e+01,4.04941428e+01,3.96371171e+01,7.32098318e-01,1.50841982e+00,3.01556282e-01,1.69080617e-01,1.99495919e+00,4.82396642e-01,5.28969144e-01,7.81932348e+01,1.45944406e+01,5.44880396e+01,1.51813153e+01,1.84625190e+01,7.75305207e+00,1.23144376e+01,8.75931711e+00,1.11614996e+01,5.37371605e+01,1.10411028e+02,3.88267862e+01,7.58618403e+01,8.39447985e+00,1.11619052e+01,4.95833085e+00,8.64960060e+00,2.97309317e+01,7.33983411e+01,3.59639912e+01,1.76040492e+00,1.93854160e+01,3.50628716e-01,4.78351753e+00,6.63353586e-01,4.07278758e+01,3.86822889e+01,4.60537832e+01,3.29478057e+01,2.67430852e+00,3.30926424e+01,1.00869292e+02,3.14653151e-01,3.27166068e+01,2.25153026e+01,2.39719951e+01,4.88387217e+01,2.16750482e+00,7.17230591e+01,1.13486490e+00,1.39718688e+01,1.72752323e+01,8.26626901e+00,3.63637688e+01,6.67731864e+01,4.53387978e+01,3.15328233e+01,3.02785723e+01,3.02746290e+01,9.90018167e+01,6.89893504e+00,9.32630672e+01,1.54628706e+01,7.24449392e+01,7.69265919e+01,2.02928029e-01,1.00696845e+01,2.62624403e+01,1.31383323e+01,2.91655950e+00,1.29899898e+01,9.65933522e+00,1.04884440e+01,6.74423099e+01,8.43570727e-01,9.59391639e+00,5.11357733e+01,1.27188358e+01,2.96886169e+01,2.03357143e+01,2.96082379e+01,5.01520173e-01,1.46602342e+01,6.18228637e+01]
p.pop(0)

3846.0313