#2024 51MCM-B题#

首先创建路径邻接矩阵，1代表联通，0代表断开。节点与自身不连通。
然后使用广度优先搜索，搜索出符合条件的五条路径

In [5]:
import numpy as np
from collections import deque
import copy

matrix = np.array([[0, 1, 0, 1, 0, 0, 0, 0, 0],[1, 0, 1, 0, 1, 0, 0, 0, 0],[0, 1, 0, 0, 0, 1, 0, 0, 0],[1, 0, 0, 0, 1, 0, 1, 0, 0],[0, 1, 0, 1, 0, 1, 0, 1, 0],[0, 0, 1, 0, 1, 0, 0, 0, 1],[0, 0, 0, 1, 0, 0, 0, 1, 0],[0, 0, 0, 0, 1, 0, 1, 0, 1],[0, 0, 0, 0, 0, 1, 0, 1, 0]])
#print(matrix)


class Graph:
    def __init__(self):
        self.graph = {0:[]}

    def add_edge(self, node, neighbors):
        self.graph[node]= self.graph.get(node,[]) + [neighbors]

class ResizableList(object):
    def __init__(self, initial_size=1722):
        self.data = [0] * initial_size
        self.size = 0
 
    def __getitem__(self, index):
        if index >= self.size:
            self._resize(index + 1)
        return self.data[index]
 
    def __setitem__(self, index, value):
        if index >= self.size:
            self._resize(index + 1)
        self.data[index] = value
        if index >= self.size:
            self.size = index + 1
 
    def _resize(self, new_size):
        self.data += [0] * (new_size - len(self.data))

In [6]:

g = Graph()
g.add_edge(0,1)
g.add_edge(0,3)
g.add_edge(1,0)
g.add_edge(1,4)
g.add_edge(2,3)
g.add_edge(2,18)
g.add_edge(3,0)
g.add_edge(3,2)
g.add_edge(3,36)
g.add_edge(3,42)
g.add_edge(4,1)
g.add_edge(4,6)
g.add_edge(5,6)
g.add_edge(5,9)
g.add_edge(5,16)
g.add_edge(5,22)
g.add_edge(6,4)
g.add_edge(6,5)
g.add_edge(6,34)
g.add_edge(7,12)
g.add_edge(7,24)
g.add_edge(7,33)
g.add_edge(8,9)
g.add_edge(8,28)
g.add_edge(8,37)
g.add_edge(8,41)
g.add_edge(9,5)
g.add_edge(9,8)
g.add_edge(9,10)
g.add_edge(10,9)
g.add_edge(10,11)
g.add_edge(10,16)
g.add_edge(10,19)
g.add_edge(11,10)
g.add_edge(11,12)
g.add_edge(11,20)
g.add_edge(11,41)
g.add_edge(12,7)
g.add_edge(12,11)
g.add_edge(12,35)
g.add_edge(13,14)
g.add_edge(13,15)
g.add_edge(13,39)
g.add_edge(14,13)
g.add_edge(14,17)
g.add_edge(14,21)
g.add_edge(15,13)
g.add_edge(15,42)
g.add_edge(16,5)
g.add_edge(16,10)
g.add_edge(16,18)
g.add_edge(16,36)
g.add_edge(17,14)
g.add_edge(17,39)
g.add_edge(18,2)
g.add_edge(18,16)
g.add_edge(18,19)
g.add_edge(18,23)
g.add_edge(19,10)
g.add_edge(19,18)
g.add_edge(19,20)
g.add_edge(19,23)
g.add_edge(20,11)
g.add_edge(20,19)
g.add_edge(21,14)
g.add_edge(22,5)
g.add_edge(22,34)
g.add_edge(22,40)
g.add_edge(23,18)
g.add_edge(23,19)
g.add_edge(24,7)
g.add_edge(24,32)
g.add_edge(25,30)
g.add_edge(25,33)
g.add_edge(26,31)
g.add_edge(26,33)
g.add_edge(27,30)
g.add_edge(27,35)
g.add_edge(28,8)
g.add_edge(28,35)
g.add_edge(29,31)
g.add_edge(29,32)
g.add_edge(30,25)
g.add_edge(30,27)
g.add_edge(31,26)
g.add_edge(31,29)
g.add_edge(32,24)
g.add_edge(32,29)
g.add_edge(33,7)
g.add_edge(33,25)
g.add_edge(33,26)
g.add_edge(34,6)
g.add_edge(34,22)
g.add_edge(34,40)
g.add_edge(35,12)
g.add_edge(35,27)
g.add_edge(35,28)
g.add_edge(36,3)
g.add_edge(36,16)
g.add_edge(37,8)
g.add_edge(38,39)
g.add_edge(38,42)
g.add_edge(39,13)
g.add_edge(39,17)
g.add_edge(39,38)
g.add_edge(40,22)
g.add_edge(40,34)
g.add_edge(41,8)
g.add_edge(41,11)
g.add_edge(42,3)
g.add_edge(42,15)
g.add_edge(42,38)
g.add_edge(27,33)
g.add_edge(33,27)
g.add_edge(26,32)
g.add_edge(32,26)
g.add_edge(6,0)
g.add_edge(0,6)
g.add_edge(21,17)
g.add_edge(17,21)
g.add_edge(37,28)
g.add_edge(28,37)
g.add_edge(35,41)
g.add_edge(41,35)
g.add_edge(6,36)
g.add_edge(36,6)
g.add_edge(41,10)
g.add_edge(10,41)
g.add_edge(38,13)
g.add_edge(13,38)
g.add_edge(2,15)
g.add_edge(15,2)
print(g.graph)

def bfs(graph, start, target):
    visited = []
    paths = []
    queue = [[start]]
    if start == target:
        return "Start = target"
    while queue:
        path = queue.pop(0)
        node = path[-1]
        neighbours = graph[node]
        for neighbour in neighbours:
            if(neighbour in path):
                continue
            new_path = list(path)
            new_path.append(neighbour)
            queue.append(new_path)
            if neighbour == target:
                if len(paths) >=5:return paths #更严格的限制
                
                if len(paths) >= 1:
                    if len(new_path) > len(paths[0]):
                        return paths
                
                paths.append(new_path)
        visited.append(node)
    return "No path"

{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [13, 17, 21], 15: [13, 42, 2], 16: [5, 10, 18, 36], 17: [14, 39, 21], 18: [2, 16, 19, 23], 19: [10, 18, 20, 23], 20: [11, 19], 21: [14, 17], 22: [5, 34, 40], 23: [18, 19], 24: [7, 32], 25: [30, 33], 26: [31, 33, 32], 27: [30, 35, 33], 28: [8, 35, 37], 29: [31, 32], 30: [25, 27], 31: [26, 29], 32: [24, 29, 26], 33: [7, 25, 26, 27], 34: [6, 22, 40], 35: [12, 27, 28, 41], 36: [3, 16, 6], 37: [8, 28], 38: [39, 42, 13], 39: [13, 17, 38], 40: [22, 34], 41: [8, 11, 35, 10], 42: [3, 15, 38]}


In [7]:
plans = [[17,6,92],
[22,4,113],
[6,22,101],
[13,26,84],
[11,28,87],
[4,17,62],
[26,15,25],
[27,26,65],
[23,24,49],
[17,29,64],
[19,33,42],
[23,10,102],
[32,34,61],
[22,10,97],
[32,23,113],
[36,18,80],
[27,8,100],
[9,34,114],
[28,20,107],
[27,40,52],
[14,17,46],
[38,33,85],
[26,40,88],
[35,23,61],
[21,19,121],
[32,20,103],
[9,31,102],
[14,6,58],
[7,16,65],
[33,35,55],
[29,9,24],
[20,25,66],
[10,40,64],
[41,7,65],
[17,8,122],
[39,30,61],
[27,17,66],
[25,20,66],
[38,20,91],
[27,6,121],
[6,3,63],
[7,26,89],
[35,22,93],
[40,27,90],
[12,24,98],
[32,39,134],
[21,38,95],
[31,15,82],
[28,40,74],
[2,19,63],
[17,29,84],
[8,37,92],
[37,33,98],
[24,28,101],
[5,40,51],
[38,33,103],
[23,31,110],
[15,20,122],
[13,23,66],
[2,22,72],
[19,23,85],
[15,1,84],
[39,11,54],
[39,29,33],
[40,8,83],
[34,18,86],
[13,4,59],
[23,2,55],
[19,25,115],
[21,13,91],
[18,15,77],
[4,15,64],
[0,5,75],
[23,32,65],
[7,14,89],
[12,3,86],
[40,10,88],
[27,17,52],
[38,14,108],
[24,21,80],
[2,4,85],
[7,26,63],
[8,13,86],
[21,36,82],
[35,39,85],
[4,22,78],
[18,37,63],
[23,16,100],
[8,14,116],
[0,17,73],
[17,0,79],
[0,35,54],
[21,40,103],
[13,23,112],
[28,24,72],
[39,20,97],
[41,21,49],
[7,39,80],
[10,13,47],
[26,28,64]]

l_org = [[0,1,315],
[0,3,393],
[1,0,200],
[1,4,231],
[2,3,667],
[2,18,790],
[3,0,615],
[3,2,424],
[3,36,730],
[3,42,618],
[4,1,200],
[4,6,246],
[5,6,405],
[5,9,545],
[5,16,282],
[5,22,529],
[6,4,200],
[6,5,403],
[6,34,520],
[7,12,829],
[7,24,512],
[7,33,395],
[8,9,517],
[8,28,321],
[8,37,200],
[8,41,276],
[9,5,678],
[9,8,392],
[9,10,389],
[10,9,205],
[10,11,495],
[10,16,574],
[10,19,479],
[11,10,541],
[11,12,561],
[11,20,606],
[11,41,261],
[12,7,758],
[12,11,707],
[12,35,519],
[13,14,419],
[13,15,868],
[13,39,227],
[14,13,513],
[14,17,200],
[14,21,200],
[15,13,598],
[15,42,200],
[16,5,328],
[16,10,554],
[16,18,473],
[16,36,469],
[17,14,290],
[17,39,517],
[18,2,635],
[18,16,576],
[18,19,497],
[18,23,397],
[19,10,453],
[19,18,388],
[19,20,522],
[19,23,506],
[20,11,240],
[20,19,368],
[21,14,210],
[22,5,377],
[22,34,305],
[22,40,230],
[23,18,480],
[23,19,467],
[24,7,472],
[24,32,325],
[25,30,200],
[25,33,316],
[26,31,237],
[26,33,442],
[27,30,350],
[27,35,831],
[28,8,371],
[28,35,418],
[29,31,200],
[29,32,200],
[30,25,289],
[30,27,200],
[31,26,200],
[31,29,200],
[32,24,323],
[32,29,266],
[33,7,200],
[33,25,293],
[33,26,505],
[34,6,279],
[34,22,270],
[34,40,340],
[35,12,410],
[35,27,767],
[35,28,606],
[36,3,501],
[36,16,557],
[37,8,272],
[38,39,407],
[38,42,821],
[39,13,375],
[39,17,315],
[39,38,406],
[40,22,247],
[40,34,200],
[41,8,280],
[41,11,494],
[42,3,974],
[42,15,200],
[42,38,460],
[27,33,442],
[33,27,340],
[26,32,200],
[32,26,289],
[6,0,226],
[0,6,370],
[21,17,321],
[17,21,200],
[37,28,200],
[28,37,272],
[35,41,637],
[41,35,521],
[6,36,200],
[36,6,298],
[41,10,475],
[10,41,483],
[38,13,365],
[13,38,434],
[2,15,688],
[15,2,921]]

possible_links = [[1,6],
                  [6,1],
[0,4],
[4,0],
[22,6],
[6,22],
[5,34],
[34,5],
[13,17],
[17,13],
[14,39],
[39,14],
[13,42],
[42,13],
[15,38],
[38,15],
[3,15],
[15,3],
[2,42],
[42,2],
[3,6],
[6,3],
[0,36],
[36,0],
[2,36],
[36,2],
[36,18],[18,36],
[3,18],[38,3],
[3,16],[16,3],
[2,16],[16,2],
[5,36],[36,5],
[6,16],[16,6],
[16,19],[19,16],
[10,18],[18,10],
[5,10],[10,5],
[9,16],[16,9],
[8,10],[10,8],
[9,41],[41,9],
[10,20],[20,10],
[11,19],[19,11],
[8,35],[35,8],
[28,41],[41,28],
[11,35],[35,11],
[12,41],[41,12],
[7,35],[35,7],
[35,33],[33,35],
[33,12],[12,33],
[12,27],[27,12],
[27,7],[7,27],
[30,33],[33,30],
[25,27],[27,25],
[32,7],[7,32],
[7,26],[26,7],
[26,24],[24,26],
[24,33],[33,24],
[33,32],[32,33],
[31,32],[31,32],
[26,29],[29,26],
]


In [8]:


def routenum(i,j):
    return 41 * i + j -42

def relationmat(route):
    relmat = ResizableList()
    while route:
        if len(route) == 1:
            break
        i = route.pop(0)
        j = route[0]
        relmat[routenum(i,j)] = 1
    return relmat


In [9]:
def largest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[-n:]
def smallest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[:n]

In [10]:
l = np.zeros(1722)
for l_i in l_org:
    l[routenum(l_i[0],l_i[1])] = l_i[2]


relmat = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    plan.append(len(routes))
    print(len(relmat))
    for route in routes:
        relmat.append(relationmat(route).data)

nprelmat = np.array(relmat)
nprelmat = nprelmat.T
print(nprelmat)


0
2
4
6
11
14
17
22
23
25
30
33
34
39
41
43
44
46
48
51
55
56
58
63
64
65
66
70
75
76
77
78
79
81
83
88
91
96
97
100
105
107
108
112
116
117
121
123
128
129
130
135
136
137
138
139
141
144
145
146
147
148
150
154
158
159
162
167
168
172
173
174
179
180
182
185
186
188
193
194
197
200
201
206
210
213
215
220
221
226
227
228
233
238
239
240
241
243
247
249
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)


##下面使用目标函数min=\Sigmax^2进行梯度下降优化

In [12]:
%%time

Q = nprelmat.T @ nprelmat
print(Q)

A = []
b = []
i = 0
for plan in plans:
    A.append(np.zeros(i).tolist() + np.ones(plan[3]).tolist() + np.zeros(len(Q) - plan[3] - i).tolist())
    b.append(plan[2])
    i += plan[3]
A = np.array(A)

[[6 4 0 ... 0 0 0]
 [4 6 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 5 3 0]
 [0 0 0 ... 3 5 0]
 [0 0 0 ... 0 0 4]]
CPU times: total: 93.8 ms
Wall time: 142 ms


In [13]:
def evaluate_max_influence(R, p):
    originload = sum(p)
    for k in range(5):
        t = R @ p
        a, _ = max(enumerate(t), key=lambda x: x[1])
        for j in range(len(R[a])):
            if R[a,j] != 0:
                p[j] = 0
    return originload - sum(p)

 ##接下来使用爬山算法进行优化

In [14]:
p = np.ones(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    plan.append(i)
    plan.append(i + plan[3])
    i += plan[3]

In [15]:
%%time
import random
import math
def list_exp(l):
    return [math.exp(x) for x in l]
#p_best = np.ones(len(Q))


CPU times: total: 0 ns
Wall time: 0 ns


In [32]:
%%time
import random
def back_fire(nprelmat, p_best):
    p = p_best
    latestmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))
    max_best = latestmax
    T = 0.01
    for i in range(50):
        fromchange = random.randint(0,len(p) - 1)
        changeamount = 0.5 * (random.random() - 0.5) * (p[fromchange]+1)
        if p[fromchange] + changeamount < 0: 
            continue
        p[fromchange] += changeamount
        if min(l - nprelmat @ p) < 0: 
            p[fromchange] -= changeamount
            continue
        if max(A @ p - b) > 0: 
            p[fromchange] -= changeamount
            continue
        tmpmax = sum(p) - evaluate_max_influence(nprelmat, copy.deepcopy(p))

        if random.random() > np.exp((tmpmax - latestmax) / T):
            p[fromchange] -= changeamount
            latestmax = tmpmax
            print("cycle:", i, "tmp:", tmpmax)
            continue
        if tmpmax > latestmax:
            latestmax = tmpmax
            print("cycle:", i, "max:", latestmax)
            
            if latestmax > max_best: 
                max_best = latestmax
                p_best = copy.deepcopy(p)
        T = 0.999 * T
    return np.append(max_best, p_best)

CPU times: total: 0 ns
Wall time: 0 ns


In [41]:
%%time


p0 = back_fire(nprelmat, np.ones(len(Q)))
p0 = p0.tolist()
effectiveness = p0.pop(0)
len_possible_links = len(possible_links)
hope_passes = np.zeros(len_possible_links)
for k in range(len_possible_links):
    possible_link = possible_links[k]
    for i in range(len(routess)):
        for j in range(len(routess[i]) - 2):
            if routess[i][j] == possible_link[0]:
                if routess[i][j+2] == possible_link[1]:
                    hope_passes[k] += p0[i]
                break

print(max(hope_passes), largest_n_indices(hope_passes, 5))
for i in largest_n_indices(hope_passes, 5):
    print(possible_links[i])


cycle: 0 max: 90.39322138008421
cycle: 2 max: 90.4537550461456
cycle: 3 max: 90.49154014845598
cycle: 7 tmp: 90.25953943025709
cycle: 8 max: 90.49154014845595
cycle: 9 max: 90.78163046797104
cycle: 10 max: 91.24124923157743
cycle: 11 max: 91.24124923157746
cycle: 18 tmp: 91.21905727662684
cycle: 19 max: 91.24124923157743
cycle: 21 max: 91.38263591872163
cycle: 22 max: 91.79952378039116
cycle: 23 max: 91.79952378039118
cycle: 30 max: 92.06685938630426
cycle: 34 max: 92.5176835903824
cycle: 39 max: 92.52497253895709
cycle: 43 tmp: 92.33742431140539
cycle: 44 max: 92.52497253895709
cycle: 48 tmp: 92.05304317342711
cycle: 49 max: 92.52497253895709
38.81418603729529 [77, 33, 53, 41, 40]
CPU times: total: 125 ms
Wall time: 305 ms


In [ ]:
import csv
# 保存列表到CSV文件
with open("E:\\Q4_result_path_notoptimized.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q4_result_res_notoptimized.csv", p_best, fmt='%f', delimiter=',')

In [ ]:
import csv
# 保存列表到CSV文件
with open("E:\\Q4_result_path.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q4_result_res.csv", p, fmt='%f', delimiter=',')

In [ ]:
load = [x for x in nprelmat @ p if x != 0]
print("stream:", load)
import copy
print(evaluate_max_influence(nprelmat, copy.deepcopy(p)))