#2024 51MCM-B题#

首先创建路径邻接矩阵，1代表联通，0代表断开。节点与自身不连通。
然后使用广度优先搜索，搜索出符合条件的五条路径

In [1]:
import numpy as np
from collections import deque

matrix = np.array([[0, 1, 0, 1, 0, 0, 0, 0, 0],[1, 0, 1, 0, 1, 0, 0, 0, 0],[0, 1, 0, 0, 0, 1, 0, 0, 0],[1, 0, 0, 0, 1, 0, 1, 0, 0],[0, 1, 0, 1, 0, 1, 0, 1, 0],[0, 0, 1, 0, 1, 0, 0, 0, 1],[0, 0, 0, 1, 0, 0, 0, 1, 0],[0, 0, 0, 0, 1, 0, 1, 0, 1],[0, 0, 0, 0, 0, 1, 0, 1, 0]])
#print(matrix)


class Graph:
    def __init__(self):
        self.graph = {0:[]}

    def add_edge(self, node, neighbors):
        self.graph[node]= self.graph.get(node,[]) + [neighbors]

class ResizableList(object):
    def __init__(self, initial_size=1722):
        self.data = [0] * initial_size
        self.size = 0
 
    def __getitem__(self, index):
        if index >= self.size:
            self._resize(index + 1)
        return self.data[index]
 
    def __setitem__(self, index, value):
        if index >= self.size:
            self._resize(index + 1)
        self.data[index] = value
        if index >= self.size:
            self.size = index + 1
 
    def _resize(self, new_size):
        self.data += [0] * (new_size - len(self.data))

In [2]:

g = Graph()
g.add_edge(0,1)
g.add_edge(0,3)
g.add_edge(1,0)
g.add_edge(1,4)
g.add_edge(2,3)
g.add_edge(2,18)
g.add_edge(3,0)
g.add_edge(3,2)
g.add_edge(3,36)
g.add_edge(3,42)
g.add_edge(4,1)
g.add_edge(4,6)
g.add_edge(5,6)
g.add_edge(5,9)
g.add_edge(5,16)
g.add_edge(5,22)
g.add_edge(6,4)
g.add_edge(6,5)
g.add_edge(6,34)
g.add_edge(7,12)
g.add_edge(7,24)
g.add_edge(7,33)
g.add_edge(8,9)
g.add_edge(8,28)
g.add_edge(8,37)
g.add_edge(8,41)
g.add_edge(9,5)
g.add_edge(9,8)
g.add_edge(9,10)
g.add_edge(10,9)
g.add_edge(10,11)
g.add_edge(10,16)
g.add_edge(10,19)
g.add_edge(11,10)
g.add_edge(11,12)
g.add_edge(11,20)
g.add_edge(11,41)
g.add_edge(12,7)
g.add_edge(12,11)
g.add_edge(12,35)
g.add_edge(13,14)
g.add_edge(13,15)
g.add_edge(13,39)
g.add_edge(14,13)
g.add_edge(14,17)
g.add_edge(14,21)
g.add_edge(15,13)
g.add_edge(15,42)
g.add_edge(16,5)
g.add_edge(16,10)
g.add_edge(16,18)
g.add_edge(16,36)
g.add_edge(17,14)
g.add_edge(17,39)
g.add_edge(18,2)
g.add_edge(18,16)
g.add_edge(18,19)
g.add_edge(18,23)
g.add_edge(19,10)
g.add_edge(19,18)
g.add_edge(19,20)
g.add_edge(19,23)
g.add_edge(20,11)
g.add_edge(20,19)
g.add_edge(21,14)
g.add_edge(22,5)
g.add_edge(22,34)
g.add_edge(22,40)
g.add_edge(23,18)
g.add_edge(23,19)
g.add_edge(24,7)
g.add_edge(24,32)
g.add_edge(25,30)
g.add_edge(25,33)
g.add_edge(26,31)
g.add_edge(26,33)
g.add_edge(27,30)
g.add_edge(27,35)
g.add_edge(28,8)
g.add_edge(28,35)
g.add_edge(29,31)
g.add_edge(29,32)
g.add_edge(30,25)
g.add_edge(30,27)
g.add_edge(31,26)
g.add_edge(31,29)
g.add_edge(32,24)
g.add_edge(32,29)
g.add_edge(33,7)
g.add_edge(33,25)
g.add_edge(33,26)
g.add_edge(34,6)
g.add_edge(34,22)
g.add_edge(34,40)
g.add_edge(35,12)
g.add_edge(35,27)
g.add_edge(35,28)
g.add_edge(36,3)
g.add_edge(36,16)
g.add_edge(37,8)
g.add_edge(38,39)
g.add_edge(38,42)
g.add_edge(39,13)
g.add_edge(39,17)
g.add_edge(39,38)
g.add_edge(40,22)
g.add_edge(40,34)
g.add_edge(41,8)
g.add_edge(41,11)
g.add_edge(42,3)
g.add_edge(42,15)
g.add_edge(42,38)
g.add_edge(27,33)
g.add_edge(33,27)
g.add_edge(26,32)
g.add_edge(32,26)
g.add_edge(6,0)
g.add_edge(0,6)
g.add_edge(21,17)
g.add_edge(17,21)
g.add_edge(37,28)
g.add_edge(28,37)
g.add_edge(35,41)
g.add_edge(41,35)
g.add_edge(6,36)
g.add_edge(36,6)
g.add_edge(41,10)
g.add_edge(10,41)
g.add_edge(38,13)
g.add_edge(13,38)
g.add_edge(2,15)
g.add_edge(15,2)
print(g.graph)

def bfs(graph, start, target):
    visited = []
    paths = []
    queue = [[start]]
    if start == target:
        return "Start = target"
    while queue:
        path = queue.pop(0)
        node = path[-1]
        neighbours = graph[node]
        for neighbour in neighbours:
            if(neighbour in path):
                continue
            new_path = list(path)
            new_path.append(neighbour)
            queue.append(new_path)
            if neighbour == target:
                if len(paths) >=5:return paths #更严格的限制
                if len(paths) >= 1:
                    if len(new_path) > len(paths[0]):
                        return paths
                paths.append(new_path)
        visited.append(node)
    return "No path"

print(g.graph)
paths = bfs(g.graph, 3, 7)
print(paths)

{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [13, 17, 21], 15: [13, 42, 2], 16: [5, 10, 18, 36], 17: [14, 39, 21], 18: [2, 16, 19, 23], 19: [10, 18, 20, 23], 20: [11, 19], 21: [14, 17], 22: [5, 34, 40], 23: [18, 19], 24: [7, 32], 25: [30, 33], 26: [31, 33, 32], 27: [30, 35, 33], 28: [8, 35, 37], 29: [31, 32], 30: [25, 27], 31: [26, 29], 32: [24, 29, 26], 33: [7, 25, 26, 27], 34: [6, 22, 40], 35: [12, 27, 28, 41], 36: [3, 16, 6], 37: [8, 28], 38: [39, 42, 13], 39: [13, 17, 38], 40: [22, 34], 41: [8, 11, 35, 10], 42: [3, 15, 38]}
{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [

##下面首先平均分配各个路径的流量，随后通过……我也不知道怎么做去完成它……

In [3]:
plans = [[17,6,92],
[22,4,113],
[6,22,101],
[13,26,84],
[11,28,87],
[4,17,62],
[26,15,25],
[27,26,65],
[23,24,49],
[17,29,64],
[19,33,42],
[23,10,102],
[32,34,61],
[22,10,97],
[32,23,113],
[36,18,80],
[27,8,100],
[9,34,114],
[28,20,107],
[27,40,52],
[14,17,46],
[38,33,85],
[26,40,88],
[35,23,61],
[21,19,121],
[32,20,103],
[9,31,102],
[14,6,58],
[7,16,65],
[33,35,55],
[29,9,24],
[20,25,66],
[10,40,64],
[41,7,65],
[17,8,122],
[39,30,61],
[27,17,66],
[25,20,66],
[38,20,91],
[27,6,121],
[6,3,63],
[7,26,89],
[35,22,93],
[40,27,90],
[12,24,98],
[32,39,134],
[21,38,95],
[31,15,82],
[28,40,74],
[2,19,63],
[17,29,84],
[8,37,92],
[37,33,98],
[24,28,101],
[5,40,51],
[38,33,103],
[23,31,110],
[15,20,122],
[13,23,66],
[2,22,72],
[19,23,85],
[15,1,84],
[39,11,54],
[39,29,33],
[40,8,83],
[34,18,86],
[13,4,59],
[23,2,55],
[19,25,115],
[21,13,91],
[18,15,77],
[4,15,64],
[0,5,75],
[23,32,65],
[7,14,89],
[12,3,86],
[40,10,88],
[27,17,52],
[38,14,108],
[24,21,80],
[2,4,85],
[7,26,63],
[8,13,86],
[21,36,82],
[35,39,85],
[4,22,78],
[18,37,63],
[23,16,100],
[8,14,116],
[0,17,73],
[17,0,79],
[0,35,54],
[21,40,103],
[13,23,112],
[28,24,72],
[39,20,97],
[41,21,49],
[7,39,80],
[10,13,47],
[26,28,64]]

def routenum(i,j):
    return 41 * i + j -42

def relationmat(route):
    relmat = ResizableList()
    while route:
        if len(route) == 1:
            break
        i = route.pop(0)
        j = route[0]
        relmat[routenum(i,j)] = 1
    return relmat

relmat = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    plan.append(len(routes))
    print(len(relmat))
    for route in routes:
        relmat.append(relationmat(route).data)

nprelmat = np.array(relmat)
nprelmat = nprelmat.T
print(nprelmat)


0
2
4
6
11
14
17
22
23
25
30
33
34
39
41
43
44
46
48
51
55
56
58
63
64
65
66
70
75
76
77
78
79
81
83
88
91
96
97
100
105
107
108
112
116
117
121
123
128
129
130
135
136
137
138
139
141
144
145
146
147
148
150
154
158
159
162
167
168
172
173
174
179
180
182
185
186
188
193
194
197
200
201
206
210
213
215
220
221
226
227
228
233
238
239
240
241
243
247
249
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)


##下面使用目标函数min=\Sigmax^2进行梯度下降优化

In [5]:
%%time

Q = nprelmat.T @ nprelmat
print(Q)

A = []
b = []
i = 0
for plan in plans:
    A.append(np.zeros(i).tolist() + np.ones(plan[3]).tolist() + np.zeros(len(Q) - plan[3] - i).tolist())
    b.append(plan[2])
    i += plan[3]

A = np.array(A)
print(A) 

#此处论文中的方法不可用，因为原来这个矩阵就已经是最简行阶梯了，前面的N列不是满秩的，所以无法求逆
P = np.append(np.append(Q, -A.T, axis=1), np.append(A, np.zeros((len(A), len(A))), axis=1), axis=0)
print(P)

np.linalg.matrix_rank(P)
#res = np.linalg.inv(P) @ np.append(np.zeros(len(Q)), b)
#print(res)
res=np.linalg.pinv(P)@np.append(np.zeros(len(Q)), b)
res = res[:len(Q)]
print("result is:", res)
print("stream:", [x for x in nprelmat @ res if x != 0])
print("Max stream:", max([x for x in nprelmat @ res if x != 0]))

[[6 4 0 ... 0 0 0]
 [4 6 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 5 3 0]
 [0 0 0 ... 3 5 0]
 [0 0 0 ... 0 0 4]]
[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[ 6.  4.  0. ... -0. -0. -0.]
 [ 4.  6.  0. ... -0. -0. -0.]
 [ 0.  0.  3. ... -0. -0. -0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
result is: [-2.48650919e+01  1.16865092e+02  4.09005289e+01  7.20994711e+01
 -8.51861903e+01  1.86186190e+02  2.14187076e+01  3.51171596e+01
 -3.56647732e+00  1.01319746e+01  2.08986355e+01  2.71703177e+01
  1.72751938e+02 -1.12922256e+02  5.71074348e+02 -1.98793843e+02
 -3.10280505e+02 -2.65410330e+01 -8.64425765e+00  1.79314725e+01
  1.21785214e+01  3.00752967e+01  6.50000000e+01  1.22674436e+01
  3.67325564e+01  2.98767968e+00 -2.19975053e+01  2.46760752e+00
  5.27637015e+01  2.77785166e+01  1.27881175e+00  1.49772637e+01
 

In [6]:
np.savetxt("E:\\p.csv", res, delimiter=',')

 ##接下来使用爬山算法进行优化

In [7]:
#首先平均分配交通量
p = np.zeros(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    plan.append(i)
    plan.append(i + plan[3])
    i += plan[3]


In [8]:
%%time
import random
latestmax = p.T @ Q @ p
for i in range(100000):
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = 0.5 * (random.random() - 0.5) * max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = p.T @ Q @ p
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", max(nprelmat @ p))
    

cycle: 4 max: 1224.5166666666669
cycle: 6 max: 1222.5840642175401
cycle: 7 max: 1222.5840642175401
cycle: 13 max: 1219.0306342785034
cycle: 16 max: 1219.0306342785034
cycle: 18 max: 1219.0306342785032
cycle: 22 max: 1219.0306342785032
cycle: 26 max: 1219.0306342785032
cycle: 29 max: 1219.0306342785032
cycle: 45 max: 1219.0306342785032
cycle: 47 max: 1219.0306342785032
cycle: 48 max: 1219.0306342785032
cycle: 57 max: 1219.0306342785032
cycle: 59 max: 1219.0306342785032
cycle: 62 max: 1219.0306342785032
cycle: 63 max: 1219.0306342785032
cycle: 77 max: 1216.3347804208788
cycle: 94 max: 1215.411484708576
cycle: 98 max: 1215.411484708576
cycle: 99 max: 1215.411484708576
cycle: 105 max: 1215.411484708576
cycle: 124 max: 1215.411484708576
cycle: 126 max: 1215.411484708576
cycle: 127 max: 1215.411484708576
cycle: 131 max: 1215.411484708576
cycle: 135 max: 1215.411484708576
cycle: 137 max: 1215.411484708576
cycle: 140 max: 1215.411484708576
cycle: 146 max: 1215.411484708576
cycle: 152 max: 1210

In [9]:
Changerate = 2

In [10]:
%%time
latestmax = max(nprelmat @ p)
for i in range(10000):
    Changerate = Changerate * 0.9999
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = Changerate * (random.random() - 0.5) *  max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = max(nprelmat @ p)
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", max(nprelmat @ p))
    

CPU times: total: 1.62 s
Wall time: 6.9 s


In [69]:
def largest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[-n:]
def smallest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[:n]

In [70]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)


In [71]:
i = 0
p = p.tolist()
for plan in plans:
    if plan[3] > 5:
        j = sorted(smallest_n_indices(p[i:i + plan[3]], plan[3] - 5), reverse=True)
        for n in j:
            routess.pop(n + i)
            p.pop(n + i)
            print(n + i)
        plan[3] = 5
    plan[4] = i
    i = i + plan[3]
    plan[5] = i
'''
relmat = []
for route in routess:
    relmat.append(relationmat(route).data)
'''
nprelmat = np.array(relmat)
nprelmat = nprelmat.T
Q = nprelmat.T @ nprelmat

30
25
59
72
96
92
91
90
88
87
86
85
84
83
135
132
170
169
163
162
178
228
238
237
236
233


In [72]:
#首先平均分配交通量
p = np.zeros(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    i += plan[3]

In [73]:
%%time
import random
latestmax = p.T @ Q @ p
for i in range(100000):
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = 0.5 * (random.random() - 0.5) * max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = p.T @ Q @ p
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", max(nprelmat @ p))
    

cycle: 1 max: 1622.6499999999996
cycle: 5 max: 1622.6499999999996
cycle: 9 max: 1622.6499999999996
cycle: 11 max: 1622.6499999999996
cycle: 24 max: 1622.6499999999996
cycle: 33 max: 1622.6499999999996
cycle: 45 max: 1622.6499999999996
cycle: 47 max: 1622.6499999999996
cycle: 60 max: 1622.6499999999996
cycle: 72 max: 1622.6499999999996
cycle: 73 max: 1622.6499999999996
cycle: 77 max: 1622.6499999999996
cycle: 81 max: 1622.6499999999999
cycle: 83 max: 1622.6499999999999
cycle: 88 max: 1622.6499999999999
cycle: 89 max: 1622.6499999999999
cycle: 98 max: 1622.6499999999999
cycle: 100 max: 1622.6499999999999
cycle: 103 max: 1622.6499999999999
cycle: 109 max: 1622.6214769194794
cycle: 115 max: 1622.6214769194794
cycle: 118 max: 1622.6214769194794
cycle: 129 max: 1621.2029453335776
cycle: 131 max: 1621.2029453335776
cycle: 137 max: 1621.2029453335776
cycle: 140 max: 1621.2029453335776
cycle: 141 max: 1614.5678694698763
cycle: 142 max: 1614.5678694698763
cycle: 145 max: 1614.5678694698763
cycle

In [74]:
Changerate = 2

In [75]:
%%time
latestmax = max(nprelmat @ p)
for i in range(10000):
    Changerate = Changerate * 0.9999
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = Changerate * (random.random() - 0.5) *  max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = max(nprelmat @ p)
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", max(nprelmat @ p))
    

cycle: 224 max: 1267.3708151591995
cycle: 517 max: 1259.866790365722
cycle: 1994 max: 1256.7512300611863
cycle: 2245 max: 1256.1967802453482
cycle: 6447 max: 1255.7395570754875
cycle: 9942 max: 1255.7243274848456
CPU times: total: 2.77 s
Wall time: 7.23 s


In [76]:
import csv
# 保存列表到CSV文件
with open("E:\\Q2_result_path.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q2_result_res.csv", p, fmt='%f', delimiter=',')