#2024 51MCM-B题#

首先创建路径邻接矩阵，1代表联通，0代表断开。节点与自身不连通。
然后使用广度优先搜索，搜索出符合条件的五条路径

In [1]:
import numpy as np
from collections import deque
import copy

matrix = np.array([[0, 1, 0, 1, 0, 0, 0, 0, 0],[1, 0, 1, 0, 1, 0, 0, 0, 0],[0, 1, 0, 0, 0, 1, 0, 0, 0],[1, 0, 0, 0, 1, 0, 1, 0, 0],[0, 1, 0, 1, 0, 1, 0, 1, 0],[0, 0, 1, 0, 1, 0, 0, 0, 1],[0, 0, 0, 1, 0, 0, 0, 1, 0],[0, 0, 0, 0, 1, 0, 1, 0, 1],[0, 0, 0, 0, 0, 1, 0, 1, 0]])
#print(matrix)


class Graph:
    def __init__(self):
        self.graph = {0:[]}

    def add_edge(self, node, neighbors):
        self.graph[node]= self.graph.get(node,[]) + [neighbors]

class ResizableList(object):
    def __init__(self, initial_size=1722):
        self.data = [0] * initial_size
        self.size = 0
 
    def __getitem__(self, index):
        if index >= self.size:
            self._resize(index + 1)
        return self.data[index]
 
    def __setitem__(self, index, value):
        if index >= self.size:
            self._resize(index + 1)
        self.data[index] = value
        if index >= self.size:
            self.size = index + 1
 
    def _resize(self, new_size):
        self.data += [0] * (new_size - len(self.data))

In [2]:

g = Graph()
g.add_edge(0,1)
g.add_edge(0,3)
g.add_edge(1,0)
g.add_edge(1,4)
g.add_edge(2,3)
g.add_edge(2,18)
g.add_edge(3,0)
g.add_edge(3,2)
g.add_edge(3,36)
g.add_edge(3,42)
g.add_edge(4,1)
g.add_edge(4,6)
g.add_edge(5,6)
g.add_edge(5,9)
g.add_edge(5,16)
g.add_edge(5,22)
g.add_edge(6,4)
g.add_edge(6,5)
g.add_edge(6,34)
g.add_edge(7,12)
g.add_edge(7,24)
g.add_edge(7,33)
g.add_edge(8,9)
g.add_edge(8,28)
g.add_edge(8,37)
g.add_edge(8,41)
g.add_edge(9,5)
g.add_edge(9,8)
g.add_edge(9,10)
g.add_edge(10,9)
g.add_edge(10,11)
g.add_edge(10,16)
g.add_edge(10,19)
g.add_edge(11,10)
g.add_edge(11,12)
g.add_edge(11,20)
g.add_edge(11,41)
g.add_edge(12,7)
g.add_edge(12,11)
g.add_edge(12,35)
g.add_edge(13,14)
g.add_edge(13,15)
g.add_edge(13,39)
g.add_edge(14,13)
g.add_edge(14,17)
g.add_edge(14,21)
g.add_edge(15,13)
g.add_edge(15,42)
g.add_edge(16,5)
g.add_edge(16,10)
g.add_edge(16,18)
g.add_edge(16,36)
g.add_edge(17,14)
g.add_edge(17,39)
g.add_edge(18,2)
g.add_edge(18,16)
g.add_edge(18,19)
g.add_edge(18,23)
g.add_edge(19,10)
g.add_edge(19,18)
g.add_edge(19,20)
g.add_edge(19,23)
g.add_edge(20,11)
g.add_edge(20,19)
g.add_edge(21,14)
g.add_edge(22,5)
g.add_edge(22,34)
g.add_edge(22,40)
g.add_edge(23,18)
g.add_edge(23,19)
g.add_edge(24,7)
g.add_edge(24,32)
g.add_edge(25,30)
g.add_edge(25,33)
g.add_edge(26,31)
g.add_edge(26,33)
g.add_edge(27,30)
g.add_edge(27,35)
g.add_edge(28,8)
g.add_edge(28,35)
g.add_edge(29,31)
g.add_edge(29,32)
g.add_edge(30,25)
g.add_edge(30,27)
g.add_edge(31,26)
g.add_edge(31,29)
g.add_edge(32,24)
g.add_edge(32,29)
g.add_edge(33,7)
g.add_edge(33,25)
g.add_edge(33,26)
g.add_edge(34,6)
g.add_edge(34,22)
g.add_edge(34,40)
g.add_edge(35,12)
g.add_edge(35,27)
g.add_edge(35,28)
g.add_edge(36,3)
g.add_edge(36,16)
g.add_edge(37,8)
g.add_edge(38,39)
g.add_edge(38,42)
g.add_edge(39,13)
g.add_edge(39,17)
g.add_edge(39,38)
g.add_edge(40,22)
g.add_edge(40,34)
g.add_edge(41,8)
g.add_edge(41,11)
g.add_edge(42,3)
g.add_edge(42,15)
g.add_edge(42,38)
g.add_edge(27,33)
g.add_edge(33,27)
g.add_edge(26,32)
g.add_edge(32,26)
g.add_edge(6,0)
g.add_edge(0,6)
g.add_edge(21,17)
g.add_edge(17,21)
g.add_edge(37,28)
g.add_edge(28,37)
g.add_edge(35,41)
g.add_edge(41,35)
g.add_edge(6,36)
g.add_edge(36,6)
g.add_edge(41,10)
g.add_edge(10,41)
g.add_edge(38,13)
g.add_edge(13,38)
g.add_edge(2,15)
g.add_edge(15,2)
print(g.graph)

def bfs(graph, start, target):
    visited = []
    paths = []
    queue = [[start]]
    if start == target:
        return "Start = target"
    while queue:
        path = queue.pop(0)
        node = path[-1]
        neighbours = graph[node]
        for neighbour in neighbours:
            if(neighbour in path):
                continue
            new_path = list(path)
            new_path.append(neighbour)
            queue.append(new_path)
            if neighbour == target:
                if len(paths) >=5:return paths #更严格的限制
                if len(paths) >= 1:
                    if len(new_path) > len(paths[0]):
                        return paths
                paths.append(new_path)
        visited.append(node)
    return "No path"

print(g.graph)
paths = bfs(g.graph, 3, 7)
print(paths)

{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [13, 17, 21], 15: [13, 42, 2], 16: [5, 10, 18, 36], 17: [14, 39, 21], 18: [2, 16, 19, 23], 19: [10, 18, 20, 23], 20: [11, 19], 21: [14, 17], 22: [5, 34, 40], 23: [18, 19], 24: [7, 32], 25: [30, 33], 26: [31, 33, 32], 27: [30, 35, 33], 28: [8, 35, 37], 29: [31, 32], 30: [25, 27], 31: [26, 29], 32: [24, 29, 26], 33: [7, 25, 26, 27], 34: [6, 22, 40], 35: [12, 27, 28, 41], 36: [3, 16, 6], 37: [8, 28], 38: [39, 42, 13], 39: [13, 17, 38], 40: [22, 34], 41: [8, 11, 35, 10], 42: [3, 15, 38]}
{0: [1, 3, 6], 1: [0, 4], 2: [3, 18, 15], 3: [0, 2, 36, 42], 4: [1, 6], 5: [6, 9, 16, 22], 6: [4, 5, 34, 0, 36], 7: [12, 24, 33], 8: [9, 28, 37, 41], 9: [5, 8, 10], 10: [9, 11, 16, 19, 41], 11: [10, 12, 20, 41], 12: [7, 11, 35], 13: [14, 15, 39, 38], 14: [

##下面首先平均分配各个路径的流量，随后通过……我也不知道怎么做去完成它……

In [3]:
plans = [[17,6,92],
[22,4,113],
[6,22,101],
[13,26,84],
[11,28,87],
[4,17,62],
[26,15,25],
[27,26,65],
[23,24,49],
[17,29,64],
[19,33,42],
[23,10,102],
[32,34,61],
[22,10,97],
[32,23,113],
[36,18,80],
[27,8,100],
[9,34,114],
[28,20,107],
[27,40,52],
[14,17,46],
[38,33,85],
[26,40,88],
[35,23,61],
[21,19,121],
[32,20,103],
[9,31,102],
[14,6,58],
[7,16,65],
[33,35,55],
[29,9,24],
[20,25,66],
[10,40,64],
[41,7,65],
[17,8,122],
[39,30,61],
[27,17,66],
[25,20,66],
[38,20,91],
[27,6,121],
[6,3,63],
[7,26,89],
[35,22,93],
[40,27,90],
[12,24,98],
[32,39,134],
[21,38,95],
[31,15,82],
[28,40,74],
[2,19,63],
[17,29,84],
[8,37,92],
[37,33,98],
[24,28,101],
[5,40,51],
[38,33,103],
[23,31,110],
[15,20,122],
[13,23,66],
[2,22,72],
[19,23,85],
[15,1,84],
[39,11,54],
[39,29,33],
[40,8,83],
[34,18,86],
[13,4,59],
[23,2,55],
[19,25,115],
[21,13,91],
[18,15,77],
[4,15,64],
[0,5,75],
[23,32,65],
[7,14,89],
[12,3,86],
[40,10,88],
[27,17,52],
[38,14,108],
[24,21,80],
[2,4,85],
[7,26,63],
[8,13,86],
[21,36,82],
[35,39,85],
[4,22,78],
[18,37,63],
[23,16,100],
[8,14,116],
[0,17,73],
[17,0,79],
[0,35,54],
[21,40,103],
[13,23,112],
[28,24,72],
[39,20,97],
[41,21,49],
[7,39,80],
[10,13,47],
[26,28,64]]

def routenum(i,j):
    return 41 * i + j -42

def relationmat(route):
    relmat = ResizableList()
    while route:
        if len(route) == 1:
            break
        i = route.pop(0)
        j = route[0]
        relmat[routenum(i,j)] = 1
    return relmat

relmat = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    plan.append(len(routes))
    print(len(relmat))
    for route in routes:
        relmat.append(relationmat(route).data)

nprelmat = np.array(relmat)
nprelmat = nprelmat.T
print(nprelmat)


0
2
4
6
11
14
17
22
23
25
30
33
34
39
41
43
44
46
48
51
55
56
58
63
64
65
66
70
75
76
77
78
79
81
83
88
91
96
97
100
105
107
108
112
116
117
121
123
128
129
130
135
136
137
138
139
141
144
145
146
147
148
150
154
158
159
162
167
168
172
173
174
179
180
182
185
186
188
193
194
197
200
201
206
210
213
215
220
221
226
227
228
233
238
239
240
241
243
247
249
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)


##下面使用目标函数min=\Sigmax^2进行梯度下降优化

In [5]:
%%time

Q = nprelmat.T @ nprelmat
print(Q)

A = []
b = []
i = 0
for plan in plans:
    A.append(np.zeros(i).tolist() + np.ones(plan[3]).tolist() + np.zeros(len(Q) - plan[3] - i).tolist())
    b.append(plan[2])
    i += plan[3]

A = np.array(A)
print(A) 

#此处论文中的方法不可用，因为原来这个矩阵就已经是最简行阶梯了，前面的N列不是满秩的，所以无法求逆
P = np.append(np.append(Q, -A.T, axis=1), np.append(A, np.zeros((len(A), len(A))), axis=1), axis=0)
print(P)

np.linalg.matrix_rank(P)
#res = np.linalg.inv(P) @ np.append(np.zeros(len(Q)), b)
#print(res)
res=np.linalg.pinv(P)@np.append(np.zeros(len(Q)), b)
res = res[:len(Q)]
print("result is:", res)
print("stream:", [x for x in nprelmat @ res if x != 0])
print("Max stream:", max([x for x in nprelmat @ res if x != 0]))

[[6 4 0 ... 0 0 0]
 [4 6 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 5 3 0]
 [0 0 0 ... 3 5 0]
 [0 0 0 ... 0 0 4]]
[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[ 6.  4.  0. ... -0. -0. -0.]
 [ 4.  6.  0. ... -0. -0. -0.]
 [ 0.  0.  3. ... -0. -0. -0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
result is: [-2.48650919e+01  1.16865092e+02  4.09005289e+01  7.20994711e+01
 -8.51861903e+01  1.86186190e+02  2.14187076e+01  3.51171596e+01
 -3.56647732e+00  1.01319746e+01  2.08986355e+01  2.71703177e+01
  1.72751938e+02 -1.12922256e+02  5.71074348e+02 -1.98793843e+02
 -3.10280505e+02 -2.65410330e+01 -8.64425765e+00  1.79314725e+01
  1.21785214e+01  3.00752967e+01  6.50000000e+01  1.22674436e+01
  3.67325564e+01  2.98767968e+00 -2.19975053e+01  2.46760752e+00
  5.27637015e+01  2.77785166e+01  1.27881175e+00  1.49772637e+01
 

In [6]:
#np.savetxt("E:\\p.csv", res, delimiter=',')

In [7]:
def evaluate_max_influence(R, p):
    originload = sum(p)
    for k in range(5):
        t = R @ p
        a, _ = max(enumerate(t), key=lambda x: x[1])
        for j in range(len(R[a])):
            if R[a,j] != 0:
                p[j] = 0
    return originload - sum(p)

 ##接下来使用爬山算法进行优化

In [8]:
#首先平均分配交通量
p = np.zeros(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    plan.append(i)
    plan.append(i + plan[3])
    i += plan[3]


In [9]:
%%time
import random
latestmax = p.T @ Q @ p
for i in range(100000):
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = 0.5 * (random.random() - 0.5) * max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = p.T @ Q @ p
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", evaluate_max_influence(nprelmat, copy.deepcopy(p)))
    

cycle: 2 max: 4316.950000000006
cycle: 5 max: 4316.950000000006
cycle: 17 max: 4316.950000000005
cycle: 24 max: 4316.950000000005
cycle: 28 max: 4316.950000000006
cycle: 29 max: 4311.657016526557
cycle: 31 max: 4311.657016526557
cycle: 35 max: 4310.652666131738
cycle: 38 max: 4321.020095674932
cycle: 39 max: 4321.020095674932
cycle: 40 max: 4321.020095674932
cycle: 41 max: 4321.020095674932
cycle: 47 max: 4311.670270172195
cycle: 50 max: 4311.670270172195
cycle: 51 max: 4311.670270172195
cycle: 61 max: 4310.520319647356
cycle: 74 max: 4307.721839273645
cycle: 75 max: 4307.721839273647
cycle: 79 max: 4304.280314910966
cycle: 84 max: 4304.280314910966
cycle: 85 max: 4304.280314910966
cycle: 90 max: 4304.280314910966
cycle: 99 max: 4304.280314910966
cycle: 104 max: 4304.310068083469
cycle: 122 max: 4304.310068083469
cycle: 127 max: 4304.0445687682895
cycle: 134 max: 4302.707944115945
cycle: 135 max: 4302.707944115945
cycle: 142 max: 4302.707944115945
cycle: 151 max: 4302.707944115945
cycl

In [10]:
Changerate = 2

In [11]:
%%time
latestmax = evaluate_max_influence(nprelmat, copy.deepcopy(p))
for i in range(10000):
    Changerate = Changerate * 0.9999
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = Changerate * (random.random() - 0.5) *  max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = evaluate_max_influence(nprelmat, copy.deepcopy(p))
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", evaluate_max_influence(nprelmat, copy.deepcopy(p)))
    

cycle: 47 max: 4176.126639026671
cycle: 54 max: 4161.1256959007105
cycle: 83 max: 4156.27199781093
cycle: 146 max: 4115.307205738584
cycle: 150 max: 4112.625894994359
cycle: 193 max: 4112.6258949943585
cycle: 427 max: 4112.418034819555
cycle: 470 max: 4112.418034819553
cycle: 498 max: 4095.8956015780464
cycle: 530 max: 4090.042567373583
cycle: 567 max: 4089.7742113678455
cycle: 590 max: 4089.7742113678437
cycle: 624 max: 4082.51220496183
cycle: 682 max: 4081.330362103167
cycle: 696 max: 4081.3303621031655
cycle: 739 max: 4081.3303621031646
cycle: 814 max: 4081.3303621031637
cycle: 816 max: 4081.3303621031628
cycle: 849 max: 4081.3303621031623
cycle: 851 max: 4081.0451216226907
cycle: 909 max: 4081.0451216226897
cycle: 910 max: 4081.045121622689
cycle: 936 max: 4075.442751836423
cycle: 1013 max: 4075.317227665377
cycle: 1072 max: 4065.33297619142
cycle: 1097 max: 4065.3329761914197
cycle: 1110 max: 4065.3329761914188
cycle: 1198 max: 4065.3329761914183
cycle: 1235 max: 4065.332976191417

In [12]:
import csv
# 保存列表到CSV文件
with open("E:\\Q2_result_path_notoptimized.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q2_result_res_notoptimized.csv", p, fmt='%f', delimiter=',')

In [13]:
restable = []
restable.append(routess)
restable.append(p)
print(p)

[5.76017041e+01 3.43982959e+01 6.29143495e+01 5.00856505e+01
 1.90749861e+01 8.19250139e+01 4.04741695e+00 1.34770206e+01
 1.14083690e+01 2.98163265e+01 2.52508670e+01 8.08893415e+00
 5.36088004e+01 2.53022654e+01 6.17165117e-02 9.62766865e-02
 6.18420068e+01 6.18807382e+00 6.29045268e+00 3.73966521e+00
 1.61536988e+00 7.16643841e+00 6.50000000e+01 3.77730958e+01
 1.12269042e+01 2.07391937e+01 4.99840258e+00 2.22718543e+01
 8.85621626e+00 7.13433315e+00 4.06942602e+00 2.74074241e+01
 1.05231499e+01 1.02000000e+02 7.44911296e-01 6.11535044e+00
 2.81735578e+01 1.08481463e+01 1.51180341e+01 3.23503363e+01
 6.46496637e+01 1.06905411e+02 6.09458886e+00 8.00000000e+01
 5.88202718e+01 4.11797282e+01 6.80045566e+01 4.59954434e+01
 7.71290379e+01 8.58650075e+00 2.12844613e+01 3.28872719e+01
 1.94900004e+00 4.03173978e+00 1.31319883e+01 4.60000000e+01
 1.31070074e+01 7.18929926e+01 3.66058908e+00 3.01419624e+01
 3.97062162e+01 1.03083148e+01 4.18291756e+00 6.10000000e+01
 1.21000000e+02 1.030000

In [14]:
def largest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[-n:]
def smallest_n_indices(lst, n):
    return sorted(range(len(lst)), key=lambda x: lst[x])[:n]

In [15]:
routess = []
for plan in plans:
    i = plan[0]
    j = plan[1]
    routes = bfs(g.graph, i, j)
    routess.extend(routes)

p = p.tolist()

In [16]:
i = 0
for plan in plans:
    if plan[3] > 5:
        #j = sorted(largest_n_indices(p[i:i + plan[3]], plan[3] - 5), reverse=True)
        j = sorted(np.random.randint(0, plan[3] - 1, plan[3] - 5), reverse=True)
        #raise ValueError("error")
        for n in j:
            routess.pop(n + i)
            p.pop(n + i)
            print(n + i)
        plan[3] = 5
        #raise ValueError("error")
    plan[4] = i
    i = i + plan[3]
    plan[5] = i
'''
relmat = []
for route in routess:
    relmat.append(relationmat(route).data)
'''
nprelmat = np.array(relmat)
nprelmat = nprelmat.T
Q = nprelmat.T @ nprelmat

In [17]:
#首先平均分配交通量
p = np.zeros(len(Q))
i = 0
for plan in plans:
    p[i:i + plan[3]] = plan[2]/plan[3]
    i += plan[3]

In [18]:
%%time
import random
latestmax = p.T @ Q @ p
for i in range(100000):
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = 0.5 * (random.random() - 0.5) * max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = p.T @ Q @ p
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", evaluate_max_influence(nprelmat, copy.deepcopy(p)))
    

cycle: 3 max: 4316.950000000006
cycle: 4 max: 4316.950000000006
cycle: 8 max: 4316.950000000006
cycle: 14 max: 4314.994362666179
cycle: 17 max: 4314.994362666179
cycle: 24 max: 4314.994362666179
cycle: 25 max: 4314.994362666179
cycle: 32 max: 4314.994362666179
cycle: 59 max: 4314.994362666179
cycle: 60 max: 4314.994362666179
cycle: 64 max: 4314.994362666179
cycle: 65 max: 4314.994362666179
cycle: 80 max: 4314.994362666179
cycle: 84 max: 4314.994362666179
cycle: 86 max: 4314.994362666179
cycle: 90 max: 4314.994362666179
cycle: 95 max: 4314.994362666179
cycle: 107 max: 4314.994362666179
cycle: 119 max: 4314.994362666179
cycle: 122 max: 4314.994362666179
cycle: 130 max: 4314.179023478014
cycle: 134 max: 4314.179023478014
cycle: 136 max: 4314.179023478014
cycle: 138 max: 4314.179023478014
cycle: 141 max: 4314.179023478014
cycle: 152 max: 4317.709744701444
cycle: 160 max: 4317.709744701444
cycle: 163 max: 4317.709744701442
cycle: 166 max: 4317.709744701442
cycle: 172 max: 4317.709744701442


In [25]:
Changerate = 0.5

In [19]:
Changerate = 2

In [26]:
%%time
latestmax = evaluate_max_influence(nprelmat, copy.deepcopy(p))
for i in range(10000):
    Changerate = Changerate * 0.9999
    plan_tmp = plans[random.randint(0, len(plans) - 1)]
    fromchange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    tochange = random.randint(plan_tmp[4], plan_tmp[5] - 1)
    changeamount = Changerate * (random.random() - 0.5) *  max(p[fromchange], p[tochange])
    if p[tochange] + changeamount < 0 or p[fromchange] - changeamount < 0: continue
    p[fromchange] -= changeamount
    p[tochange] += changeamount
    tmpmax = evaluate_max_influence(nprelmat, copy.deepcopy(p))
    if tmpmax > latestmax:
        p[fromchange] += changeamount
        p[tochange] -= changeamount
        continue
    if tmpmax < latestmax:
        latestmax = tmpmax
        print("cycle:", i, "max:", evaluate_max_influence(nprelmat, copy.deepcopy(p)))  

cycle: 15 max: 3901.9774798548624
cycle: 193 max: 3901.9774798548615
cycle: 432 max: 3901.9501299496415
cycle: 519 max: 3901.9501299496405
cycle: 628 max: 3901.9501299496396
cycle: 672 max: 3901.9153000387096
cycle: 1292 max: 3901.797778019035
cycle: 1330 max: 3901.797778019034
cycle: 1536 max: 3901.797778019033
cycle: 1986 max: 3901.549406946164
cycle: 1999 max: 3901.5080989377866
cycle: 2595 max: 3901.5080989377857
cycle: 2967 max: 3901.508098937785
cycle: 3084 max: 3901.508098937784
cycle: 3739 max: 3901.508098937783
cycle: 3785 max: 3901.0814056683294
cycle: 6981 max: 3901.037402630551
cycle: 7724 max: 3901.03740263055
cycle: 8391 max: 3900.3788721793862
CPU times: total: 1min
Wall time: 1min 7s


In [27]:
import csv
# 保存列表到CSV文件
with open("E:\\Q2_result_path.csv", 'w', newline='') as f:
    writer = csv.writer(f)
    for routes in routess:
        writer.writerow([routes])


#np.savetxt("E:\\Q1_result_path.csv", routess, fmt='%d', delimiter=',')
np.savetxt("E:\\Q2_result_res.csv", p, fmt='%f', delimiter=',')

In [28]:
load = [x for x in nprelmat @ p if x != 0]
print("stream:", load)
import copy
print(evaluate_max_influence(nprelmat, copy.deepcopy(p)))

stream: [80.46635544428769, 310.11141897497737, 1012.2033840965141, 1210.8620366882951, 387.9233027285258, 152.12869899917897, 477.21562807676634, 266.7977178384911, 191.18446112458463, 240.80215097102774, 316.62255139725676, 177.10241720156552, 588.5482686057244, 16.70320550540019, 176.5336445557124, 162.94080063043918, 362.4517313942754, 213.23683221450688, 976.7635225312865, 465.0, 412.17837894943557, 444.1699264483166, 123.553144838454, 155.0, 170.11537303469396, 540.3429834382316, 328.45379502948606, 298.8092550199634, 214.81355564210756, 345.44230179998834, 742.7264044287102, 506.7368475035828, 591.3678260210781, 599.5697579018112, 622.7912592163316, 469.19376462947537, 65.6165899757592, 790.1783789494359, 967.1374249044252, 122.38341002424085, 473.08472522181535, 1100.67099793222, 118.71555836243476, 268.1307629658772, 732.8139123890563, 77.08472522181513, 129.00000000000003, 1210.8326525729158, 766.2154881876925, 96.3914021139932, 217.64903763905238, 623.8580675509976, 513.2848